### ISSUE TITLE
Windows Service Events

### ISSUE THREAD

**Issue by k2niner** [ocsf/ocsf-schema#1020]
Windows Service activity doesn't cleanly map. May need to add a class to Windows Profile or modify Process Activity [1007].

From OMB M-21-31 (for Windows Logging):
- Service Status Changes (Start, Stop, Fail, Restart, etc.)
- Service Failures and Restarts
- Process Creation and Termination

**Comment by mikeradka** [comment]
Following thorough deliberation in recent System Activity sync meetings, we've concluded that the current class set is insufficient for capturing Windows Service events. 

Our proposed action is to draft a pull request (PR) to integrate a dedicated Windows Service Events class into the Windows Extension.

**Comment by mikeradka** [comment]
Note: we could also look into windows service modifications

**Comment by davemcatcisco** [comment]
I didn't see this issue before. [T1543.003](https://attack.mitre.org/techniques/T1543/003/) ("Create or Modify System Process: Windows Service") is one of the most commonly used sub-techniques for achieving the Persistence and Privilege Escalation tactics on Windows. It is crucial that we can adequately express this, and I agree with Mike that it should be a dedicated event in the System Activity category in the Windows extension. The event should be able to express anything that happen to a service, i.e.

- Create
- Change Config
- Enable
- Disable
- Start
- Pause
- Resume
- Stop
- Delete

I'm happy to have a go at a PR for this if people like.

**Comment by davemcatcisco** [comment]
I've created a draft PR to address this issue: https://github.com/ocsf/ocsf-schema/pull/1103

**Comment by mikeradka** [comment]
Closing this out, as it was address in PR #1103
