### ISSUE TITLE
'Share' attribute descriptions too specific to SMB

### ISSUE THREAD

**Issue by mikeradka** [ocsf/ocsf-schema#1022]
In the dictionary, the `share` attributes are specific to SMB, but `share` attributes could be used in other classes. While currently, Core OCSF only references the `share` attributes in the `SMB Activity Event`, I see an opportunity to use these objects in an extension class I would like to enhance.

I think we should broaden the name of these attributes:

<img width="794" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/91983279/4299bd68-1c43-4e50-8ccb-a65ce3779466">

| attribute         | existing desc | new desc |
|----------------|:-----:|-----------:|
| share                | The SMB share name. |  The share name. See specific usage. |
| share_type.     | The SMB share type, normalized to the caption of the share_type_id value. In the case of 'Other', it is defined by the event source. | The share type, normalized to the caption of the share_type_id value. In the case of 'Other', it is defined by the event source.  |
| share_type_id | The normalized identifier of the SMB share type. | The normalized identifier of the share type. |

**Comment by pagbabian-splunk** [comment]
Is this a 2.0 breaking change based on your label?  Did you mean 1.2?  Otherwise LGTM

**Comment by mikeradka** [comment]
> Is this a 2.0 breaking change based on your label? Did you mean 1.2? Otherwise LGTM

Nice catch! Fixed the labels

**Comment by mikeradka** [comment]
Merged
