### ISSUE TITLE
Add `ext` attribute to `File` object

### ISSUE THREAD

**Issue by shellcromancer** [ocsf/ocsf-schema#1043]
The [File](https://schema.ocsf.io/1.2.0-rc.1/objects/file?extensions=) object currently has an attribute for the file name (e.g. `svchost.exe`) but having a dedicated attribute for the executable extension (e.g. `exe`) is useful to search on to reduce the need for more expensive wild-card searches on the name field. This would also allow for security use-cases like finding where the mime-type differs from expected file extensions. 

Other security object models in usage today have this attribute as well:
- ECS: [File extension](https://www.elastic.co/guide/en/ecs/current/ecs-file.html#field-file-extension)
- CybOX: [File_Extension](https://cyboxproject.github.io/documentation/objects/#file)

I'd suggest the type of the attribute be an optional string, and it would follow the same conventions as ECS to only get the trailing extension if there are multiple, without the prepending `.`: `file.name` of `export.tar.gz` has a `file.extension` of `gz`.

**Comment by zschmerber** [comment]
Nice, this is a good find.
