### ISSUE TITLE
 Discrepancy in Validation Failure Output

### ISSUE THREAD

**Issue by mikeradka** [ocsf/ocsf-schema#1047]
I encountered a Schema Validation issue with our Github Actions. Despite repeatedly receiving the message `FAILED: Required keys are present`, the validation problem stemmed from a missing attribute in the dictionary. Upon adding the attribute, the failure message ceased. Could we explore enhancing the output of our validation process? With the discrepancy in messaging, there were recurrent validation failures without a clear path to resolution, as the message implied a required field needed fixing.

<img width="443" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/91983279/d311f45f-81e0-4a25-98b1-8ecbcd091104">

----
- Example Failure ('required keys' message): https://github.com/ocsf/ocsf-schema/actions/runs/8729744683/job/23952309619#step:5:112
- What fixed it (added a dictionary attribute): https://github.com/ocsf/ocsf-schema/pull/1014/commits/0f432f7f945f7a81e746b52a98427c1ff08460fd

**Comment by alanisaac** [comment]
I'm going to leave the second bullet alone for now, and close this as is.  The other two bullets have been implemented, and should help with both making the error more prominent and the resolution more clear.
