### ISSUE TITLE
Add "Update" to activity ID to Application lifecycle (6002) 

### ISSUE THREAD

**Issue by zschmerber** [ocsf/ocsf-schema#1054]
<img width="1657" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/13574947/a0c4357a-bf00-40fe-aa55-3990daee653c">
We need to add "Update" to activity ID so updates can be represented in this class.

**Comment by mikeradka** [comment]
We discussed this in the 04/24/2024 System call and determined that in addition we should also add:

- `Enable`
- `Disable`
- `Restart`

Created PR #1064 to have these added.
