### ISSUE TITLE
Network Connection Information doesn't have the ability to display allowed or blocked

### ISSUE THREAD

**Issue by matt-soi** [ocsf/ocsf-schema#1079]
It would be good if the Network Connection Information object had a field for allowed or blocked so that information could be passed on to the Detection Findings class when an IDS is involved.

**Comment by jonrau-at-queryai** [comment]
Have you taken a look at the `security_control` Profile? It adds `disposition_id` which normalizes this data - allowed, block, reject, etc.

**Comment by matt-soi** [comment]
Yep. That has worked great actually. I will close this.
