### ISSUE TITLE
All first release objects merged into main

### ISSUE THREAD

**Issue by jp-harvey** [ocsf/ocsf-schema#115]
First release Objects, checkbox checked when merged into main.
- [ ] API Details
- [ ] Attack
- [ ] Authorization Information
- [ ] CVSS Scores
- [ ] Client
- [ ] Cloud
- [ ] Compliance Details
- [ ] Container
- [ ] DNS Answer
- [ ] DNS Query
- [ ] Device
- [ ] Device Hardware Info
- [ ] Digital Certificate
- [ ] Digital Signature
- [ ] Display
- [ ] Distributed Computing Environment/Remote Procedure Call (DCE/RPC)
- [ ] Endpoint
- [ ] Enrichment
- [ ] Event Origin
- [ ] Event Source
- [ ] Extended User
- [ ] Feature
- [ ] File
- [ ] Finding Details
- [ ] Fingerprint
- [ ] Geo Location
- [ ] Group
- [ ] HTTP Cookie
- [ ] HTTP Header
- [ ] HTTP Request
- [ ] HTTP Response
- [ ] Identity
- [ ] Identity Provider
- [ ] Image
- [ ] Job
- [ ] Kernel Resource
- [ ] Keyboard Information
- [ ] Malware
- [ ] Managed Entity
- [ ] Metadata
- [ ] Module
- [ ] Network Connection Information
- [ ] Network Endpoint
- [ ] Network Interface
- [ ] Network Proxy
- [ ] Network Traffic
- [ ] OS
- [ ] Object
- [ ] Observable
- [ ] Peripheral Device
- [ ] Process
- [ ] Product
- [ ] Registry Key
- [ ] Registry Value
- [ ] Related Findings
- [ ] Remediation Details
- [ ] Request Elements
- [ ] Resource
- [ ] Response Elements
- [ ] Rule
- [ ] Server
- [ ] Service
- [ ] Session
- [ ] Subject Alternative Name
- [ ] TLS Extension
- [ ] Transport Layer Security (TLS)
- [ ] Uniform Resource Locator
- [ ] User
- [ ] Vulnerability Details

**Comment by paveljos** [comment]
These are merged into main; object reviews will be handled by work-stream owners
