### ISSUE TITLE
All first release categories completed and merged into main

### ISSUE THREAD

**Issue by jp-harvey** [ocsf/ocsf-schema#116]
First release Categories, checked if complete and merged into main:

- [ ] System Activity
- [ ] Findings
- [ ] Audit Activity
- [ ] Network Activity
- [ ] Cloud Activity
- [ ] Container Activity
- [ ] Database Activity
- [ ] Application Activity
- [ ] Configuration / Inventory

**Comment by paveljos** [comment]
In place for primary consideration. Will continue to review as needed.
