### ISSUE TITLE
Provide means to indicate a file at the referenced path was deleted

### ISSUE THREAD

**Issue by antchan2** [ocsf/ocsf-schema#1192]
The [File object](https://schema.ocsf.io/1.3.0/objects/file?extensions=) does not have a means to indicate the file at the referenced `path` was deleted. This is meaningful as it can justify why other fields such as `hashes` could not be populated. An example use case is on Linux where it is possible for a program to delete its own executable file after the process is running. Examining the executable path of such a process using the `/proc/[pid]/exe` symlink yields a path with the string ["(deleted)" appended to the end](https://elixir.bootlin.com/linux/v5.19.17/source/fs/d_path.c#L254-L255). A process deleting its own executable can be a sign of defence evasion.

I propose adding an optional `is_deleted` field.

**Comment by pagbabian-splunk** [comment]
Seems reasonable.  Can you create a PR?
