### ISSUE TITLE
Event Origin object

### ISSUE THREAD

**Issue by floydtree** [ocsf/ocsf-schema#120]
1. Define structure of the `origin` object 
2. Clean up & refine originally present attributes under the origin object
3. Move `origin` under `metadata`
4. Revert related changes made in this https://github.com/ocsf/ocsf-schema/commit/1e5b116105ddeeb445979581c0da3a1ba7d6fa5b

More context - [slack convo](https://opencybersecu-lz97379.slack.com/archives/C03C2QJRA73/p1659045687574909)
Original object for reference - 

```
{
  "caption": "Event Origin",
  "name": "event_origin",
  "description": "The event origin is where the event was created.",
  "extends": "object",
  "attributes": {
    "cloud": {},
    "container": {},
    "customer_uid": {},
    "device": {
      "requirement": "recommended"
    },
    "feature": {},
    "product": {
      "requirement": "recommended"
    }
  },
  "constraints": {
    "at_least_one": [
      "device",
      "product"
    ]
  }
}
```

**Comment by paveljos** [comment]
https://github.com/ocsf/ocsf-schema/discussions/190
https://github.com/ocsf/ocsf-schema/discussions/191
https://github.com/ocsf/ocsf-schema/discussions/192
