### ISSUE TITLE
Environment Variable object's is_attribute_truncated is ambiguous 

### ISSUE THREAD

**Issue by antchan2** [ocsf/ocsf-schema#1215]
The [Environment Variable](https://schema.ocsf.io/1.4.0-dev/objects/environment_variable?extensions=) object was [introduced in the 1.4.0 draft](https://github.com/ocsf/ocsf-schema/commit/d4a370bacad5e3b0d2e736d0fe25bcb6d1ec312d) and the meaning of the new `is_attribute_truncated` field is ambiguous. It describes:

> Whether the `name` or `value` of the environment variable has been truncated.

It would be clearer if there are separate attributes indicating whether `name` was truncated and/or `value` was truncated.

**Comment by antchan2** [comment]
This issue has been resolved by @davemcatcisco in commit https://github.com/ocsf/ocsf-schema/commit/e03d175642ef7e3609a543a6943555b6babb413e through the introduction of a new `long_string` type

**Comment by davemcatcisco** [comment]
Oh, thanks @antchan2 - I forgot the close this issue.
