### ISSUE TITLE
Provide means to report kernel releases for Linux Operating Systems

### ISSUE THREAD

**Issue by rebeccasenger** [ocsf/ocsf-schema#1242]
# Summary

The [Operating System (OS)](https://schema.ocsf.io/1.3.0/objects/os?extensions=) object does not currently have a way to specify kernel information. The motivation behind this issue is that Linux allows the kernel to be “mixed and matched” for a given distribution version. For example, a user running Ubuntu 20.04 could be running the kernel release 5.15.0-118-generic or 5.15.0-122-generic or 5.15.0-100-generic, etc. None of the other existing fields in the OS object seem like a good fit for storing this information. Rather than using an already existing field improperly, I propose we either create a new Linux specific field or object in the OS object to contain the kernel release.

# Potential Options

## Option A: Add new `linux_kernel_info` object to `os` object via Linux extension

Make a new `linux_kernel_info` object under the Linux extension to contain all of the linux specific kernel information we may want to store, including a field for `kernel_release`. The benefit of making a new object instead of just a new field is that the object can have many fields added to it and can thus be extended/added to over time. This option can make adding Linux specific kernel info easier in the future. Then we can add the `linux_kernel_info` object to the `os` object via a Linux extension.

Pros:
- Windows and Linux can have their own specific objects (`linux_kernel_info` and potentially a future `windows_kernel_info`)
- Extensible

Cons:
- We only have one field to populate in `linux_kernel_info` currently.

## Option B: Linux and Windows specific `kernel` object

There already exists a `kernel` object, but it represents [Kernel Resources](https://schema.ocsf.io/1.3.0/objects/kernel?extensions=), which seems very Windows specific. We could deprecate this object and replace it with new `kernel` objects that can be specific to Linux and Windows.  

Pros: 
- Windows and Linux can have their own specific implementations of the object
- Extensible
- `kernel` object will better match the MITRE definition of kernel: https://d3fend.mitre.org/dao/artifact/d3f:Kernel/

Cons
- Do not know if existing `kernel` object is currently being used

**Comment by jonrau-at-queryai** [comment]
Good addition & idea overall!

Do you have any idea what the Attributes for the new `kernel` objects would look like?

**Comment by rebeccasenger** [comment]
> Do you have any idea what the Attributes for the new kernel objects would look like?

For starters on the Linux side I would be interested in adding a "kernel_release" field, for example:
```
"kernel_release": {
    "caption": "Kernel Release",
    "description": "The kernel release of the operating system. Determined from the <code>uname -r</code> command output on Unix-based systems.",
    "type": "string_t"
}
```

**Comment by jonrau-at-queryai** [comment]
We'll probably discuss it tomorrow (5 NOV 2024) for sure, if it's only that one Attribute (or a handful) I can see us just add it to `os` directly to keep the schema "flatter" so to speak. There is also precedence for OS specific data in there already with `os.sp_name` and what not

...hell, `os.sp_name` is where I stick nix kernel info right now 😬

**Comment by mikeradka** [comment]
Thanks for raising this. If we need any more time to discuss it, we could always use the Wednesday System Activity sync.

**Comment by rebeccasenger** [comment]
Here is an example of how Option B would be implemented: https://github.com/rebeccasenger/ocsf-schema/pull/1

**Comment by rebeccasenger** [comment]
Spoke about this issue again in the OCSF System Activities call. We decided on an Option C:

Add a new `kernel_release` attribute to the OS object. It will be available for both Linux and Mac. Then we can have a detailed description on the expected contents for Unix based systems and for Windows. It will be optional.
