### ISSUE TITLE
Time attributes name consistency

### ISSUE THREAD

**Issue by rroupski** [ocsf/ocsf-schema#126]
There are many time attribute, see the picture. The names are not very consistent. Some use nouns, others use past tense verbs. We should pick one form only.

<img width="2393" alt="image" src="https://user-images.githubusercontent.com/2128145/182671821-48bc2b3d-3a97-452f-b90a-fc819e015921.png">

**Comment by floydtree** [comment]
first_occurence/last_occurence to be replaced by first_seen_time/last_seen_time from the dev extension
