### ISSUE TITLE
Process' environment variables array can be simplified

### ISSUE THREAD

**Issue by antchan2** [ocsf/ocsf-schema#1272]
The 1.4.0-dev draft added the ability to store a Process' environment variables as an array. To accommodate situations where the variable's name and/or value are very long and must be truncated, the [long_string](https://github.com/ocsf/ocsf-schema/blob/f42effc1b1b99105b9e1ddaa11f0afa2d8bda141/objects/long_string.json#L5) object was used as it provides built-in truncation indicators. However, when `long_string` is used in an array, as it is appropriate for storing multiple environment variables, the output data can be overly complex. @zschmerber shared in the `system-activity` Slack channel the following example:

```
"environment_variables": [{
		"variable_name": {
			"value": "UPDATE_IS_MACHINE"
		},
		"variable_value": {
			"value": "0"
		}
	}, {
		"variable_name": {
			"value": "PATH"
		},
		"variable_value": {
			"value": "/usr/bin:/bin:/usr/sbin:/sbin"
		}
	}],

```

We should revisit the `environment_variable` object definition and seek ways to simplify the data representation.

**Comment by antchan2** [comment]
During the course of the conversation I proposed considering `labels`, an array of strings already defined in the [dictionary](https://schema.ocsf.io/1.3.0/dictionary), to optionally indicate truncation. That simplifies the output for the more common non-truncation case. I recall this general approach was also discussed when `environment_variables` was first added. This is an example output:

```
"environment_variables": [{
			"name":"NAME",
			"value":"VALUE"
		}, {
			"name":"VERY_LONG_NAM",
			"value": "VALUE",
			"labels": ["name_truncated"]
		}, {
			"name":"NAME3",
			"value": "VERY_LONG_VALU",
			"labels": ["value_truncated"]
		}, {
			"name":"VERY_LONG_NAM4",
			"value": "VERY_LONG_VALU",
			"labels": ["name_truncated", "value_truncated"]
		}],
		...
```

**Comment by zschmerber** [comment]
I think this is much cleaner thanks @antchan2 !

**Comment by mikeradka** [comment]
@antchan2 @zschmerber I like the thought process here. Could we dig into this one on a little bit during the 12/13/24 System Call?

**Comment by antchan2** [comment]
@mikeradka Sure. I can join that call.

**Comment by mikeradka** [comment]
Note: `name` and `value` are of `String` data type rather than `Long String` data type.

**Comment by antchan2** [comment]
This issue was discussed in detail in the December 11 system-activity call. While using labels to indicate truncation is a practical solution, there was concern that the use of hardcoded strings to annotate fields in the same object is not ergonomic and we prefer not to make this a precedent in the 1.4 draft.

We considered other options including:
- Using the [Key:Value](https://schema.ocsf.io/1.4.0-dev/objects/key_value_object?extensions=) object, which can optionally express Value as a string array, and store a truncation indicator (e.g., `"..."`) in the second element 
- Storing the environment variables as an array of [long strings](https://schema.ocsf.io/1.4.0-dev/objects/long_string?extensions=), where each string contains "NAME=VALUE", which removes one level of object depth
- Storing the entire environment variables list as a long string, similar to what has been done for [script content](https://schema.ocsf.io/1.4.0-dev/objects/script?extensions=).  

However, all of these proposed solutions have drawbacks, including:
1. Allowing a single environment variable name to be associated with multiple values is not intuitive (i.e., inconsistent with there use by operating systems)
2. Storing “NAME=VALUE" as one string, and having one truncation indicator, but leaves ambiguous whether it was NAME and/or VALUE that was truncated.
3. Storing the full environment variable list as a long string provides truncation indication, but leaves ambiguous where it occurred 

Since there is consensus change is needed for the upcoming 1.4 draft, recognizing `environment_variables` is a new field, and that in practice truncation is rate, my suggestion for a balanced solution is to:
1. Focusing on specifying what is essential (i.e., the environment name and values), 
2. Expressing them in the most natural format (arguably an array of key-value pairs),
3. Ensure minimal object depth, and
4. Leaves the door door for adding truncation indicators should a real need arise in the future.

I propose in 1.4 we remove the truncation indicator altogether for now and  keep `environment_variable` as a distinct object (i.e., not reuse the Key:Value object).  This way we keep the design simple and intuitive with the ability to extend in the future. If an implementation needs to indicate truncation _right now_, it can still use tactics like appending `"..."` to the end of the string. This is not ideal as it can  be ambiguous, but likely good enough. OCSF won’t offer specific guidance for truncation for now. 

I've updated the [draft PR](https://github.com/antchan2/ocsf-schema/pull/9) accordingly. Nominally, environment variables would be stored like this:

```
"environment_variables": [{
			"name":"NAME1”,
			"value":"VALUE1”
		}, {
			"name":"NAME2”,
			"value":"VALUE2”
		}],
…
``` 

An implementation that cares about truncation _could_ do this:

```
"environment_variables": [{
			"name":"NAME1”,
			"value":"VALUE1”
		}, {
			"name":"NAME2”,
			"value”:”VERY_LONG_VALU…”
		}, {
			"name”:”VALUE_LONG_NAM…”,
			"value”:”VALUE2”
		}],
…
```

@zschmerber @mikeradka @mlmitch

**Comment by mlmitch** [comment]
This is definitely cleaner. The possibility of extending in the future is good too.
