### ISSUE TITLE
Define details about container hash

### ISSUE THREAD

**Issue by fkautz** [ocsf/ocsf-schema#152]
In the container schema, the following item is defined:

```json
  "sha2": {
      "description": "Commit hash of image created for docker or the SHA256 hash of the container. For example: a3bf90e006b2.",
      "group": "context",
      "requirement": "optional"
    },
```

The field "sha2" is ambiguous in a few respects:

* the hash should be of the container image, not the container itself.
* sha2 itself is a set of six cryptographic hash functions: SHA-224, SHA-256, SHA-384, SHA-512, SHA-512/224, SHA-512/256. Some of these hashed have the same output size, so you can't always meaningfully tell them apart.
* The encoding should be explicitly defined. Hex is probably the most common, but there are other candidates that yield shorter strings.

Finally, it may make sense to define this as a set of hashes. If sha256 is broken, it'll be easier to adapt to a set of hashes rather than a specifically hard coded value. One good example we can follow is from the In-Toto project where hashes are presented in a dictionary object with each hash explicitly listed, rather than attached to the root object. See https://github.com/in-toto/docs/blob/v0.9/in-toto-spec.md#421-hash-object-format for more information.

Hope this all helps! I'm happy to open these changes as a pull request if that would be useful.

**Comment by fkautz** [comment]
Also, it would be helpful to list both the container id and image id explicitly when available rather than combine them into a single field where they can be either.

**Comment by colek42** [comment]
here is the spec for ImageID:  https://github.com/opencontainers/image-spec/blob/main/config.md#imageid

**Comment by rroupski** [comment]
We should use the [fingerprint](https://schema.ocsf.io/objects/fingerprint) instead of sha1, shar2, etc.

**Comment by paveljos** [comment]
Cleaned up thanks to @rroupski 's work above.
