### ISSUE TITLE
Consider defining a JSON schema

### ISSUE THREAD

**Issue by tschmidtb51** [ocsf/ocsf-schema#161]
As far as I checked, none of the JSON files currently refers to a JSON schema. I would like to suggest to define JSON schemas to make sure that changes in these files are valid according to the rules.

I'm happy to submit a PR but I might need some help to fully understand some design decisions.

**Comment by rroupski** [comment]
Note, the JSON schema is not flexible enough to cover the definition used in the OCSF json files, therefore the JSON schema is not used.

**Comment by davaya** [comment]
The charter says "The schema framework definition files and the resulting normative schema are written as JSON."

Presumably "the JSON schema" refers to IETF [Internet Draft](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01), but the term could apply to other schema languages such as CDDL with a JSON preface.  Unless someone is planning to write normative requirements to validate data against the OCSF definition files, some schema language will be needed.

OCSF may wish to consider OASIS [JSON Abstract Data Definition (JADN)](https://github.com/oasis-tcs/openc2-jadn/blob/published/jadn-v1.0-cs01.md), a UML-based format-independent schema language.  JADN currently defines bindings to human oriented JSON, machine-to-machine oriented concise JSON, and concise binary object representation ([CBOR](https://www.rfc-editor.org/rfc/rfc8949.html)).  But the intent of an abstract schema is to be able to define bindings to other performance-oriented data formats such as Protobuf, Avro, or FIX/[SBE](https://www.fixtrading.org/standards/sbe-online/), based on developer interest.

"Flexibility" would be accomplished by pre-processing - logical models are typically UML structured classifiers, but schemas are simple classifiers that define Datatypes.  Some deterministic algorithm must be defined to convert the OCSF JSON files into Datatypes against which data instances can be validated.

**Comment by davaya** [comment]
The charter says "The schema framework definition files and the resulting normative schema are written as JSON."

Presumably "the JSON schema" refers to the IETF [Internet Draft](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01), but the term could apply to other schema languages such as CDDL with a JSON preface. Unless someone is planning to write normative requirements to validate data against the OCSF definition files, some schema language will be needed.

OCSF may wish to consider OASIS [JSON Abstract Data Notation (JADN)](https://github.com/oasis-tcs/openc2-jadn/blob/published/jadn-v1.0-cs01.md), a UML-based format-independent schema language. JADN currently defines bindings to human oriented JSON, machine-to-machine oriented concise JSON, and concise binary object representation ([CBOR](https://www.rfc-editor.org/rfc/rfc8949.html)). But the intent of an abstract schema is to be able to define bindings to other performance-oriented data formats such as Protobuf, Avro, or FIX/[SBE](https://www.fixtrading.org/standards/sbe-online/), based on developer interest.

"Flexibility" would be accomplished by pre-processing - logical models are typically UML structured classifiers, but schemas are simple classifiers that define Datatypes. Some manual or automated process will need to convert the OCSF JSON files into Datatypes against which data instances can be validated.

**Comment by paveljos** [comment]
Triaged this ticket; we will create a feature request to generate JSON-schema from the schema server API.

**Comment by rroupski** [comment]
The JSON-schema server API is available now, so closing this issue.
