### ISSUE TITLE
Reference to Missing https://github.com/ocsf/ocsf-server

### ISSUE THREAD

**Issue by PritamDutt** [ocsf/ocsf-schema#173]
I want to review OCSF as a consumer of OCSF schema. 
After reviewing all the available documentation, only related reference I could find was in [Contributing.MD](https://github.com/ocsf/ocsf-schema/blob/main/CONTRIBUTING.md)

However, the linked repo is not accessible. 

Kindly share the link to updated repository.

Thanks,

```
## Using OCSF as a consumer 

See [ocsf-server](https://github.com/ocsf/ocsf-server) documentation.
```

**Comment by rroupski** [comment]
The link to the repo is correct, however the schema server repos is still private.

**Comment by PritamDutt** [comment]
Thanks @rroupski any plans on making it public? or you recommend some other way to understand more of schema, and its application

**Comment by rroupski** [comment]
The repo is public now and the link should work.
