### ISSUE TITLE
Review the usage of the Virtual Machine object

### ISSUE THREAD

**Issue by rroupski** [ocsf/ocsf-schema#180]
Currently the [Virtual Machine](https://schema.ocsf.io/objects/virtual_machine) object is used by the [Cloud Virtual Machine](https://schema.ocsf.io/classes/cloud_vm) event.

Are there any other applicable use cases? For example, virtual machines are used on a desktop or laptop computer.

**Comment by paveljos** [comment]
This opened up a much larger conversation regarding the cloud category. Will be discussed with those category and class owners.
