### ISSUE TITLE
Clean up the unused attributes from the core schema

### ISSUE THREAD

**Issue by rroupski** [ocsf/ocsf-schema#183]
The dictionary has a few unused attributes, which should be removed from the core schema.
<img width="1855" alt="image" src="https://user-images.githubusercontent.com/2128145/186773172-fa069753-3296-4804-a876-a6268aa1002a.png">

**Comment by paveljos** [comment]
Is this completed by https://github.com/rroupski/ocsf-schema/commit/1f8a3ed07ed6fb34d2527c1372f08bd074cc1314 ?

**Comment by floydtree** [comment]
`http_cookies`, `quarantine_uid`
