### ISSUE TITLE
New Data Type: ByteString

### ISSUE THREAD

**Issue by irakledibm** [ocsf/ocsf-schema#205]
It is common to transport some data, such as payloads etc in form of byte array, without converting it. To cover those use cases we need to add new data type "bytestring_t" to represent immutable sequence of bytes. We can add it as subset of String with base64 encoding or as base type.

**Comment by irakledibm** [comment]
Related poll: https://github.com/ocsf/ocsf-schema/discussions/206

**Comment by rroupski** [comment]
When a text-based encoding is used, such as JSON, what would be the format for the bytestring_t data?

**Comment by irakledibm** [comment]
Implemented in https://github.com/ocsf/ocsf-schema/pull/228
