### ISSUE TITLE
Unexpected behavior on event validation with Profiles

### ISSUE THREAD

**Issue by tankbusta** [ocsf/ocsf-schema#222]
If you try to validate a event via the route `/api/validate` with one that implements the `User` profile you get the following error

Sent (other fields omitted):
```
{
    "profiles": ["User"],
    "user": {
       "uid": "<SID goes here>"
    }
}
```

Error:
```
{
    "user": {
        "error": "Undefined attribute name",
        "value": {
            "uid": "<SID goes here>"
        }
    }
}
```

Changing `User` to `user` causes the event to validate successfully. I would consider making the profile lookup case insensitive to prevent issues like this as the Schema uses the `caption` vs the `name`

**Comment by rroupski** [comment]
Try `user` all lower case. The profile names are all lower case.

{
    "profiles": ["user"],
    "user": {
       "uid": "<SID goes here>"
    }
}

**Comment by rroupski** [comment]
Not an issue -- works as expected.

**Comment by tankbusta** [comment]
@rroupski Yes, using a lowercase `user` fixed it (I noted that), but unless you go look at `profiles/user.json` you wouldn't know to use `user` vs `User`. Instinctively, folks are going to use `User` as that's the Profile name shown throughout the Schema UI

<img width="110" alt="image" src="https://user-images.githubusercontent.com/592749/191069015-6b1fe638-8ff2-436b-9e39-0908f8936302.png">
