### ISSUE TITLE
Description of product object in the file object.

### ISSUE THREAD

**Issue by floydtree** [ocsf/ocsf-schema#245]
The current description of `product` object nested inside the `file` object doesn't accurately represent its usage (snapshot below). A new and specific description will need to be added at an object level, [here](https://github.com/ocsf/ocsf-schema/blob/442c6e7cea5d1497a9680c94df3bad1b07986e37/objects/file.json#L71) to clarify the intentional use-case.

![Screen Shot 2022-09-27 at 2 10 59 PM](https://user-images.githubusercontent.com/89877409/192603987-fa6007cb-de7d-463a-9af1-4e6ee8ce6cad.png)

**Comment by rroupski** [comment]
Right, this is the default description of the `product` attribute and it should be overwritten in the file object.
