### ISSUE TITLE
Support remote process memory & handle operations in Process Activity 

### ISSUE THREAD

**Issue by Noafr** [ocsf/ocsf-schema#253]
SentinelOne Distinguishes between different Remote Process Activities. Code Injection & Process Termination are covered by Activity ID 4 (Inject) & 2 (Terminate), however missing Remote Memory Operations (e.g. readLsass, writeToEAT, libraryRemoteWrite, remoteAlloc) as well as Remote Handle Operations (Duplicate Process Handle, Duplicate Thread Handle, Open Remote Process Handle)

**Comment by Noafr** [comment]
Have we determined our next steps here?

**Comment by rroupski** [comment]
Add process as target to Memory Activity
Add `read` and `write` activity id. See WriteProcessMemory

**Comment by tankbusta** [comment]
Open Remote Process Handle can be handled with Process Activity with `activity_id` 3
