### ISSUE TITLE
Virtual Machine Activity

### ISSUE THREAD

**Issue by jasonbreimer** [ocsf/ocsf-schema#254]
### Problem
Currently Virtual Machine Activity has been moved to System Activity from Cloud Activity. All agree that Cloud Activity is not a good place but System Activity may also not be the best fit.

### Suggestion
We discussed during yesterday's System Activity Workstream that Container Activity Category would be a better fit for Virtual Machine Activity. This activity could contain hypervisor based activities and contain both virtual machine and container activities. These types represent similar technologies and they should go together under Container Activity.

### Suggested Next Step
1. Move Virtual Machine Activity to Container Activity
2. Modify Container Activity name/description to better reflect its purpose.

**Comment by floydtree** [comment]
Move Cloud Activity to Container activity? Typo?

**Comment by Aniak5** [comment]
@jasonbreimer this makes a lot of sense to me.
