### ISSUE TITLE
Add 'Trigger' Activity ID to Scheduled Job Activity

### ISSUE THREAD

**Issue by Noafr** [ocsf/ocsf-schema#263]
**Problem**
The Scheduled Job Activity doesn`t contain an activity id to represent an event when a new trigger is created, either time-based trigger or an event-based trigger

**Suggestion**
Add 'Trigger' Activity ID to Scheduled Job Activity

**Comment by tankbusta** [comment]
Is this to indicate a trigger was added to an existing Scheduled Task or a Scheduled Task was executed because a task's event trigger was fulfilled and caused it to execute? 

If it's adding/modifying an event trigger, I'd say Activity ID 2 (Updated) should be used.

**Comment by Noafr** [comment]
This is to indicate a trigger was added to an existing scheduled task.
Anyway, using the "Update" value makes sense -  should I close this one?

**Comment by tankbusta** [comment]
I can close it for you - thanks for clarifying!
