### ISSUE TITLE
Add 'Import' Activity ID to Registry Key Activity 

### ISSUE THREAD

**Issue by Noafr** [ocsf/ocsf-schema#265]
**Problem**
The Registry Key Activity doesn`t contain an activity id to represent an event when the registry key is imported to the registry

**Suggestion**
Add 'Import' Activity ID to Registry Key Activity

**Comment by Aniak5** [comment]
@Noafr do you want `import` and `export` to the `registry_value_activity` as well?

**Comment by Noafr** [comment]
No need from my side, thanks
