### ISSUE TITLE
Named Pipe activity to move from Kernel Activity to File Activity 

### ISSUE THREAD

**Issue by Noafr** [ocsf/ocsf-schema#267]
**Problem**
Named pipes are currently listed under the Kernel Activity Category. 

**Proposal**
Like most IPC mechanisms, pipes help facilitate communication between two applications and or processes using shared memory. 
This shared memory is treated as a file object in the Windows operating system. Since pipes are treated as file objects, standard file object functions such as ReadFile() and WriteFile(), which are exposed via the Windows Application Programming Interface (API), are commonly used during communication. With that in mind, named pipes activity should reside under the File Activity Category.

**Comment by rroupski** [comment]
Does the name pipe have the required attributes of the file object?
