### ISSUE TITLE
Simplification of Profiles in data and API calls

### ISSUE THREAD

**Issue by floydtree** [ocsf/ocsf-schema#276]
Define the usage of `metadata.profiles` in data and consequently update the API to a schema.

[More Context](https://opencybersecu-lz97379.slack.com/archives/C03C2QPSBPB/p1664571197421779)

Potential path ahead.

1. `metadata.profiles` is made a `required` field. 
2. If your data contains no profiles `metadata.profiles`, set an empty array
    1. Does absence of field mean there are no profiles set?
    2. In that case, does it allow for `metadata.profiles` to remain optional?
4. If your data contains x, y profiles `metadata.profiles` = [x, y]

Utilize the same strategy in the API calls.

**Comment by paveljos** [comment]
Let's move this to a proposal, option 1.) make profiles required, and 2.) optional profiles, unset = no profiles.
