### ISSUE TITLE
Event attributes missing requirement

### ISSUE THREAD

**Issue by davaya** [ocsf/ocsf-schema#290]
All objects appear to define the requirement level of their attributes.

Many event attributes do not have a requirement level:
  (raw_data, enrichments, ref_event_code/name/uid, status_code/detail, unmapped, count, duration, end_time, start_time, ...)

Some event attributes do have a requirment level:
  (message, metadata, observables, severity/id, status, status_id, time, ref_time, timezone_offset, activity, ...)

This seems inconsistent - if events are named aggregates of attributes, the requirement level for each attribute in an event should be specified unless there is a default requirement level.

**Comment by rroupski** [comment]
the default is `optional`.
