### ISSUE TITLE
OCSF doesn`t provide information on the event original threat value/score 

### ISSUE THREAD

**Issue by Noafr** [ocsf/ocsf-schema#297]
**Problem**
Users may want to query for the threat score of the event as given by the ref (original) source. Vectra (AI-driven threat detection and response for hybrid and multi-cloud enterprises), for example, sends the $threat field which is a value between 0 to 80. Analysts that are used to working with Vectra may want to query for something like `ref_severity = 67 ` which is more specific than our current normalized range for the severity column (values between 1-6). 

**Suggestion** 
`ref_severity` (suggested field name) should be added to the base event to reflect the threat score/severity given by the source. 
The field should be of type string as different vendors might send this data differently (for example, Okta sends a Severity field as type string (DEBUG, INFO, WARN, ERROR etc.))

**Comment by floydtree** [comment]
The current `severity` field addresses your concern. 

![Screen Shot 2022-10-10 at 12 51 28 PM](https://user-images.githubusercontent.com/89877409/194916415-9c60a235-c680-473e-ade4-b84c3d3d7f37.png)

---

I would qualify this line by stating that how we handle such pairs (severity/severity_id, status/status_id et al) across OCSF is still under debate and consideration. You are welcome to join the discussion [here](https://opencybersecu-lz97379.slack.com/archives/C03KF0TELR0/p1664558269455089) on slack.

**Comment by Noafr** [comment]
Thank you - I've been told the "severity" column is just a reflection of the severity id (e.g. "Low", "Critical" etc.).

**Comment by Noafr** [comment]
Why Malware object? Not all events are classified as malware. Why not add the raw_score (I`d vote for ref_score) to the base event?

**Comment by Aniak5** [comment]
We are proposing a general purpose solution for all reference attributes to the original data.

**Comment by pagbabian-splunk** [comment]
reference to original data has the naming convention of `ref_`.  I can see it maybe could be used outside of Malware however if we are considering it to be a "threat score" rather than an arbitrary score, then Base Event may be too general of a location.  Do we have knowledge of where we want to apply threat scores such that we can consider where it should reside?

**Comment by Aniak5** [comment]
This issue has been addressed within [this PR](https://github.com/ocsf/ocsf-schema/pull/323).
