### ISSUE TITLE
Product UID in Finding Details Object

### ISSUE THREAD

**Issue by rroupski** [ocsf/ocsf-schema#333]
The **Finding Details Object** has `product_uid` attribute with the following description: "_The unique identifier of the product that reported the finding_". What is the difference between `metadata.product` (_the product that created the event/finding_) and the `finding.product_uid`?

Also, the `product_uid` is used in the **Related Findings Object** `{product_uid: string, uid: string}`, which is used in the **Finding Details Object** as an array. If the `uid` identifies the finding, then do we really need the `product_uid` in the **Related Findings Object**?

**Comment by irakledibm** [comment]
I agree that it is a bit odd to have product_uid and Metadata.product. I think that Metadata.product is sufficient.

**Comment by floydtree** [comment]
The current scheme is required if you consider a finding aggregator scenario. Imagine, an aggregator tool like Security Hub reporting findings from a provider like Crowdstrike, in this case, `metadata.product` will account for Security Hub details, where as finding.product_uid will account Crowdstrike details.
