### ISSUE TITLE
Missing 7 in the reputation.score_id enum values

### ISSUE THREAD

**Issue by rroupski** [ocsf/ocsf-schema#334]
The number 7 is missing in `reputation.score_id` enum values. Should we define it?

<img width="1475" alt="image" src="https://user-images.githubusercontent.com/2128145/199598765-bd8ec344-ca72-45e3-8d5c-84dbf8f51c19.png">

**Comment by Aniak5** [comment]
@rroupski we should have a 7, how about a caption of `Suspicious` and a description of `Indicators of suspicious behavior`?
