### ISSUE TITLE
Replace correlation_uid in Metadata Object with Correlation Details Object.

### ISSUE THREAD

**Issue by irakledibm** [ocsf/ocsf-schema#342]
There are few gaps in Metadata Object when it comes to event correlation.
1. Product that reported event and product that correlated events could be different. 
2. Sometimes correlation_uid may not be produced by product, but it may provide set of correlation keys or other attributes contributing to correlation algorithm. Considering that this would be vendor/product specific, I would suggest to introduce correlation "data" json attribute. Also I would recommend to add correlation "details" attribute.
```
{
  "caption": "Correlation Details",
  "name": "correlation_details",
  "extends": "object",
  "attributes": {
    "correlation_uid": {
      "requirement": "recommended"
    },
    "product": {
      "requirement": "recommended"
    },
    "details": {
      "requirement": "optional"
    },
    "data": {
      "requirement": "optional"
    }
  }
}
```

**Comment by pagbabian-splunk** [comment]
This has been here for a while, but if the use case is a SIEM that correlates events into a finding, that is covered by related_events in the Finding Details object, so we would not need a Correlation Details object.

**Comment by irakledibm** [comment]
makes sense
