### ISSUE TITLE
Revisit DHCP event class

### ISSUE THREAD

**Issue by Aniak5** [ocsf/ocsf-schema#347]
The DHCP event class contains a `network_interface` and a `relay` currently. We need to make it more clear that the `network_interface` is the client requesting a new lease. We also do not have any attribute encapsulating the DHCP server nor a response field to convey the assigned ip address.

**Comment by mr-splunk** [comment]
For something to refer to, here is an example Infoblox DHCP ACK event:

Raw Syslog Format:
```
<30>Sep 28 10:15:46 192.168.1.2 dhcpd[13613]: DHCPACK on 192.168.1.120 to 11:22:33:44:55:66 (dummyhostname123) via eth1 relay eth1 lease-duration 600 (RENEW) uid 99:88:77:66:55:44:33
```

OCSF Translation:
```
{
  "activity_id": 5,
  "category_uid": 4,
  "class_uid": 4004,
  "event_time": "Sep 28 10:15:46",
  "is_renewal": true,
  "lease_time": 60,
  "message": "DHCPACK on 192.168.1.120 to 11:22:33:44:55:66 (dummyhostname123) via eth1 relay eth1 lease-duration 600 (RENEW) uid 99:88:77:66:55:44:33",
  "metadata": {
    "profiles": [],
    "uid": "74dcc9d2-096b-470c-9321-4d144a3441d5",
    "version": "0.27.0"
  },
  "network_interface": {
    "hostname": "dummyhostname123",
    "ip": "192.168.1.120",
    "mac": "11:22:33:44:55:66",
    "name": "eth1",
    "type_id": 0,
    "uid": "99:88:77:66:55:44:33"
  },
  "origin": {
    "device": {
      "ip": "192.168.1.2",
      "os": {
        "name": "Linux",
        "type_id": 200
      },
      "type_id": 1
    },
    "feature": {
      "name": "DHCP"
    },
    "product": {
      "name": "Infoblox"
    }
  },
  "ref_event_name": "DHCPACK",
  "relay": {
    "name": "eth1",
    "type_id": 0
  },
  "severity_id": 1,
  "time": 1668033713132,
  "unmapped": {
    "facility": 3,
    "pid": "13613"
  }
}
```

(mileage may vary slightly on that OCSF translation, as it was created using an older pre-release version of OCSF. But this gives the general application of RELAY in action)

**Comment by Aniak5** [comment]
The [DHCP zeek log](https://docs.zeek.org/en/master/scripts/base/protocols/dhcp/main.zeek.html) contains the most comprehensive fields from any other log we have looked at. We can see both the src and dst endpoints, their ports, the requested ip and the assigned ip.
