### ISSUE TITLE
Refactor the Cloud API event class into a Cloud API profile applied to multiple event classes

### ISSUE THREAD

**Issue by pagbabian-splunk** [ocsf/ocsf-schema#371]
The Cloud API class is intended to capture a wide variety of service control plane events produced through AWS Cloudtrail, as well as through GCP Cloud Logging and Azure Activity systems.  The class structure is not flexible enough for a few reasons:

1. API activity is not only cloud API activity.  The class is in a Cloud specific category but will move to the Audit Activity category but its class name is cloud specific.
2. The current class includes Login and IAM activity IDs that also are in the Authentication and Authorization classes in the Audit Activity category.  It is preferable to have all Auth and IAM activity in one class (e.g. Azure uses Azure AD for login, which is akin to AD for non-cloud), even if it is logged through the same facility (e.g. Cloudtrail) that logs other operations.
3. Much of the Cloud API activity falls into the very general Operation activity ID, although some of the cloud plane operations are general for virtual machines (e.g. EC2, App Engine) and storage (e.g. S3, Azure Blob, G Cloud Storage) which have their own classes.  It would be better for the events pertaining to a service's API activity to be with its other logged activity (e.g. Create Virtual Machine, Create Storage Bucket).
4. Some of the Cloud API activity pertains to access, however our Access Activity class is in the Application Activity category, even though it can be more general than for applications.  E.g. GCP breaks its Cloud Logging into Data Access, along with Admin Activity, System Event, Policy Denied audit logs.
5. Virtualization Activity (Virtual Machine Activity, Container Activity) may also have Cloud API events and benefit from its attributes.
6. Cloud Storage Activity may also have events reported via Cloud API events (i.e. via Cloudtrail, et al)

Hence my proposal is
1. we take the unique attributes from the Cloud API and create a new profile, either named 'Cloud API' or 'Control Plane'.  The attributes are: `api, http_request, identity, resources, src_endpoint`.
2. we create a new class called `API Activity` in the `Audit` category with a single `activity_id` for `API Operations` or better yet, generic values such as CRUD (along with Other and Unknown).  The class would include a Required `api` API Details attribute.  This class can accommodate the `Cloud API` profile attributes and when applied ends up essentially identical to the current `Cloud API` event class.  The differences are: the category is now `Audit Activity` as was planned; the class name is `API Activity` rather than `Cloud API Activity`; the `activity_id` enum no longer has `Login` or `IAM` and the `Operation` is renamed `API Operation` or the more generic CRUD operations.
3. we apply the `Cloud API` profile to the `Authentication` and `Authorization` classes for those control plane operations, rather than overload the `API Activity` class and in the process split those operations way from their dedicated classes.
4. we move the `Access Activity` class from the `Application Activity` category and move it to the `Audit Activity` category.  It can now also apply the `Cloud API` profile for access log events if needed.  The class should be evaluated to see if it can be more general than its current activities (e.g. can it serve as a class for Apache access logs?).
5. The `Cloud API` profile can be applied to the `Virtual Machine Activity` `Container Lifecycle Activity` and the `Cloud Storage Activity` so that any control plane logging via those APIs can be converged with the corresponding services (e.g. EC2, S3, etc.).  The CRUD functions for `Container Lifecycle Activity` need to be updated to include `Read` and `Update` at minimum (see the K8S logging documentation).

**Comment by pagbabian-splunk** [comment]
One more small comment: I noticed that the `Cloud Storage Activity` class effectively uses the proposed profile as it already has the same four attributes ( `api, http_request, identity, resources, src_endpoint`).  Presumably this pattern can exist elsewhere as well.

**Comment by floydtree** [comment]
To dos - 
1. Remove Cloud Activity Category
2. Move Cloud API to AAA/Audit as API activity w/ Cloud profile
3. Redefine Cloud Profile
4. Rename Database Activity category to Data/Storage activity
5. Move Cloud Storage to the new category
