### ISSUE TITLE
Should `metadata.profiles` be a required field?

### ISSUE THREAD

**Issue by johan1252** [ocsf/ocsf-schema#375]
## Issue

Currently if validating an event without `metadata.profiles` field, the behaviour of `/api/validate` defaults to assuming certain profiles are in-use.

Example by default it assumes `cloud` is a required field even though according to the ocsf-schema it's only required if `cloud` profile is enabled.
<img width="636" alt="Screen Shot 2022-11-25 at 11 46 52 AM" src="https://user-images.githubusercontent.com/6536680/203897263-8e69ef60-2e8a-4daf-9024-6f242858642d.png">
<img width="644" alt="Screen Shot 2022-11-25 at 11 47 02 AM" src="https://user-images.githubusercontent.com/6536680/203897270-3f8f5e2c-b2e7-46a6-ad98-fb0404c1b478.png">

Currently `profiles` is not a required field in `metadata`.
https://github.com/ocsf/ocsf-schema/blob/main/objects/metadata.json#L22

## How to reproduce

Use the following sample event with the [/api/validate api](https://schema.ocsf.io/api/doc/index.html#/Tools/SchemaWeb_SchemaController_validate).
Observe that without setting `metadata.profiles` field, the response is missing required attribute `cloud`.
<img width="1389" alt="Screen Shot 2022-11-25 at 11 46 23 AM" src="https://user-images.githubusercontent.com/6536680/203897174-1f51ad54-9310-4627-99d1-c3a59e6109d0.png">

Adding `profiles: []` to `metadata` field allows for the event to be validated successfully.
<img width="752" alt="image" src="https://user-images.githubusercontent.com/6536680/203897360-b59b78c3-0f11-47ea-b7a6-0fbe0973a84b.png">

Sample event:
```
{
   "activity_id":1,
   "activity_name":"Generate",
   "category_name":"Findings",
   "category_uid":2,
   "class_name":"Security Finding",
   "class_uid":2001,
   "confidence":0,
   "finding":{
      "desc":"typically i nightlife",
      "src_url":"der destroyed io",
      "title":"great vernon resistant",
      "uid":"811376ca-6c5b-11ed-82db-0242ac110002"
   },
   "message":"canal carry teach",
   "metadata":{
      "modified_time":1669337578172543,
      "original_time":"lot ocean intended",
      "processed_time":1669337578172574,
      "product":{
         "lang":"en",
         "name":"grams walking lock",
         "uid":"8113aea6-6c5b-11ed-9019-0242ac110002",
         "vendor_name":"broadcast pb eos",
         "version":"0.33.0"
      },
      "version":"0.33.0"
   },
   "resources":[
      {
         "group_name":"organization gst ford",
         "labels":[
            "sh"
         ],
         "name":"directory cancer brighton",
         "owner":"Cathey Tamra",
         "uid":"81135974-6c5b-11ed-a15b-0242ac110002"
      },
      {
         "account_uid":"81135e24-6c5b-11ed-8f69-0242ac110002",
         "cloud_partition":"national does argentina",
         "group_name":"man increased department",
         "name":"pickup richmond state",
         "owner":"Lavera Wilber",
         "region":"gregory course decent",
         "uid":"81136d10-6c5b-11ed-b048-0242ac110002"
      }
   ],
   "severity":"Medium",
   "severity_id":3,
   "state":"Unknown",
   "state_id":0,
   "status":"Success",
   "status_id":1,
   "time":1669337578171130,
   "type_name":"Security Finding: Generate",
   "type_uid":200101,
   "vulnerabilities":[
      {
         "cve":{
            "created_time":1669337578171474,
            "cvss":{
               "base_score":48.0321,
               "vector_string":"commissioners need board",
               "version":"0.33.0"
            },
            "type":"authors pr nba",
            "uid":"8113855c-6c5b-11ed-9183-0242ac110002"
         },
         "references":[
            "merchandise nasdaq shades"
         ],
         "related_vulnerabilities":[
            "amazon arbor formed"
         ]
      }
   ]
}
```

**Comment by rroupski** [comment]
That's is the current implementation, which is if no `profiles` are specified in then data, then the event is validated using ALL profiles that applicable to the event class. Otherwise the `profiles` specifies zero or more profiles to be used in the validation.

The main reason for that behavior is that there is no good value to specify ALL profiles in a list of strings attribute.

**Comment by pagbabian-splunk** [comment]
My issue with no profiles = all profiles is that if I want to search all events of a certain profile, say Malware, those that have the profile Malware will not show up, because the profiles array is missing.  This is also inconvenient for producers and mappers, as if a basic event class such as File Activity should not have any profiles, an empty profiles array MUST be present.  I would want it to be the other way around.

**Comment by johan1252** [comment]
Thanks @rroupski @pagbabian-splunk for the background information.

I feel similar to @pagbabian-splunk that making `profiles` be explicit would be easier as an end user.
Right now, not including `profiles` gives behaviour that feels surprising without knowing the underlying details. For example in the schema browser by default attributes from profiles are not shown, which contradicts how the validation logic works.

Regarding the need for allowing "ALL profiles", is there an actual use case for this? It feels safer to me to force users to define each profile they want to apply so that any new profiles added in the framework don't apply automatically to existing schemas. No surprises if the user specifically says which profiles they want to use. However...guess this depends how many profiles we are expecting there to be in the future (no one would want to list 20+ profiles for example).

**Comment by rroupski** [comment]
OK, should I make the `profiles` a required attribute? 

Change the current behavior as if the `profiles` is null/missing then assume no profiles are used?

**Comment by johan1252** [comment]
> OK, should I make the `profiles` a required attribute?
> 
> Change the current behavior as if the `profiles` is null/missing then assume no profiles are used?

Personal preference is changing the behaviour of `profiles` that if they are missing assume no profiles are used.
If you go with that change then the `profiles` attribute doesn't need to be a required attribute.

**Comment by pagbabian-splunk** [comment]
_"OK, should I make the profiles a required attribute?

Change the current behavior as if the profiles is null/missing then assume no profiles are used?"_

If the profiles attribute is required, then it can't be missing.  We have the option of it being Optional but still having the behavior above.  However, for example, System Activity classes should all be required to have the Host profile (as it is essentially baked in).  If the profiles attribute is Optional, it would be difficult to enforce this Host value being populated.

**Comment by rroupski** [comment]
I updated the server to treat missing profiles as empty profiles, e.g. profiles = [].

**Comment by Aniak5** [comment]
Since profiles are optional this will be optional as well.
