### ISSUE TITLE
Replace smtp_activity with email_delivery_activity

### ISSUE THREAD

**Issue by ablyler** [ocsf/ocsf-schema#379]
There are two classes for email activities `smtp_activity` and `email_delivery_activity`. `smtp_activity` appears to be a lower-level implementation that could be replaced with the more rich `email_delivery_activity` class that is in the dev extension. My proposal is to remove `smtp_activity` and promote the `email_delivery_activity` and related email items from the dev extension.

**Comment by ablyler** [comment]
Thoughts @rroupski and @Aniak5?

**Comment by Aniak5** [comment]
We should at the very least update the `activity_id` within the `smtp_activity` class with the ones from the `email_delivery_activity` class. There are some fields within the `email_delivery_activity` class that are redundant to some of the fields we obtain from extending the `network_activity` class such as `receiver_ip`, `device` and `sender_ip`. So we shouldn't just replace the `smtp_activity` class but it seems like a good idea to take a subset of the fields within the `email_delivery_activity`  class that are missing and not redundant to the `smtp_activity` class.

**Comment by rroupski** [comment]
I agree with @ablyler, the smtp_activity class seems redundant because it does not add any attributes or activity id's compare to the network_activity class and we should remove it. The SMTP connection/traffic can be reported as network_activity event (the connection_info identifies the protocol).

**Comment by ablyler** [comment]
@Aniak5 what are your thoughts on @rroupski response?

**Comment by Aniak5** [comment]
Are y'all suggesting to remove the SMTP event class and move the `email_delivery_activity` from dev to main? Or just to remove SMTP event class altogether with no further actions? @ablyler and @rroupski

**Comment by ablyler** [comment]
Updating this for completeness, we discusses in a meeting today that the intent is to remove the SMTP event class and move the `email_delivery_activity` from dev to main.

**Comment by rroupski** [comment]
@ablyler are we happy with the email event classes? Should we move them to the core schema? Perhaps we can talk about the tomorrow on the OCSF meeting?

**Comment by ablyler** [comment]
@rroupski I have a few proposed changes to the email event classes; I will put them up in a PR this week. We can for sure talk about this more at the OCSF meeting tomorrow.
