### ISSUE TITLE
Email Events

### ISSUE THREAD

**Issue by debaduttar** [ocsf/ocsf-schema#382]
### Discussed in https://github.com/ocsf/ocsf-schema/discussions/377

<div type='discussions-op-text'>

<sup>Originally posted by **debaduttar** November 28, 2022</sup>
Hi,
I am new to OCSF and trying to understand the schema. 
How Email Delivery Finding event (Finding category) and Email Activity Event (System Activity category) are related? Do they exist independent of each other? Why they are not in the same category?

Apologies for the very basic question but will appreciate if I can get a answer👍 .

Regards
Deb    </div>

**Comment by rroupski** [comment]
There is no more Email Delivery Finding event in Finding category.
