### ISSUE TITLE
Lack of actor property on Virtual Machine Activity

### ISSUE THREAD

**Issue by rroupski** [ocsf/ocsf-schema#387]
### Discussed in https://github.com/ocsf/ocsf-schema/discussions/386

<div type='discussions-op-text'>

<sup>Originally posted by **overly-engineered** December  2, 2022</sup>
I've been looking at the various events provided by OCSF, and many of them combine two or more entities into a single event. The virtual machine activity doesn't.

There is no actor field on it, so I can describe what happened to a given VM but not what the instigator of that change was.

What was the reason behind this decision?</div>

**Comment by floydtree** [comment]
We can look into this class while addressing - https://github.com/ocsf/ocsf-schema/issues/371 (the cloud api activity refactorization)
