### ISSUE TITLE
'file' object: change the user string attributes to user objects

### ISSUE THREAD

**Issue by mr-splunk** [ocsf/ocsf-schema#391]
The `file` object contains four _Optional_ user attributes which are currently just free-form strings:

- `accessor`
- `creator`
- `modifier`
- `owner`

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/91983279/206285917-dc806595-311c-4e50-a4fc-e071fb7730e7.png">
<img width="945" alt="image" src="https://user-images.githubusercontent.com/91983279/206285978-8ea680a6-5b60-4581-a894-79ec5b7fe059.png">
<img width="968" alt="image" src="https://user-images.githubusercontent.com/91983279/206286045-8c8fad9a-a163-45a9-9551-5ca8b5915cd3.png">
<img width="969" alt="image" src="https://user-images.githubusercontent.com/91983279/206286093-ddd0a15c-ef03-4581-96b0-7955adcd34bc.png">

Leaving these free-form goes against the regular consistency with the OCSF `user` object, and very much limits the capability to map specific user attributes to the accessor, creator, etc. etc. Such as the user's e-mail, full name, org, or other details.

I am proposing that we keep the attribute names the same (`accessor`, `creator`, `modifier`, and `owner`), but change them from string types to user objects. This would allow to map attributes such as:

- `creator.email_addr`
- `owner.name`
- `modifier.domain`

In addition, doing so would make them useful observables. 
For reference, here is the user object:

<img width="1351" alt="image" src="https://user-images.githubusercontent.com/91983279/206287148-96502d18-b3f4-49a2-b51e-f8d8b4f53ead.png">

**Comment by tankbusta** [comment]
Because the `user` object only has recommended fields and no requirements, I think this change makes a lot of sense. The value you would put in those 4 fields would be inside the user object as `name`

**Comment by jasonbreimer** [comment]
This is a great suggestion and also aligns better with FIM solutions.
