### ISSUE TITLE
Registry Key/Value: Result inconsistency

### ISSUE THREAD

**Issue by tankbusta** [ocsf/ocsf-schema#393]
In reviewing the Registry Key/Value classes I noticed the requirements on `reg_value` and `reg_value_result` (s/value/key for the other class, same holds true) should be changed to an `either or` required constraint. 

## Proposal

Change the requirement on these event classes to `reg_value` OR `reg_value_result` MUST be set. 

## Examples

Using Windows APIs as an example as some tools still rely on hooking (and sysmon outputs data in this format)...

### On the subject of Getting a Registry Value:

Documentation: [RegGetValueW](https://learn.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-reggetvaluew)

OCSF would expect `activity_id` to be set to `Read` with `reg_value` set. Inside `reg_value` `path` would be set to a combination of `hKey + lpSubKey`, `name` set to the value of `lpValue`, and `pvData` would be `data`

### On the subject of Deleting a Registry Value:

Documentation: [RegDeleteKeyValueW](https://learn.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regdeletekeyvaluew)

OCSF would expect `activity_id` to be set to `Delete` with `reg_value` set. Inside `reg_value` `path` would be set to a combination of `hKey + lpSubKey` and `name` set to the value of `lpValueName`.

### On the subject of Modifying a Registry Value:

Documentation: [RegSetKeyValueW](https://learn.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regsetkeyvaluew)

OCSF would expect `activity_id` to be set to `Modify` with `reg_value_result` set. Inside `reg_value` `path` would be set to a combination of `hKey + lpSubKey`, `name` set to the value of `lpValueName`, and `pvData` would be `data`

**Comment by rroupski** [comment]
@tankbusta Currently, `reg_key` and `reg_value` are required and `reg_key_result` and `reg_value_result` are optional. The `reg_key_result` and `reg_value_result` should be only used with `Modify` to specify the new value/key for registry.

I am not sure what exactly is the issue? Is `activity_id` = `Modify` the problem? Because the current values are unknown/not available?

**Comment by awhite456** [comment]
From an analyst perspective, having the field you want to access change depending on the operation type (`reg_value` for Get/Set/Delete and `reg_value_result` for Modify) is not optimal. 

Would it be preferable to have `reg_value_before` (or similar) as an optional field for the Modify case, and have `reg_value` always set for Get/Set/Delete/Modify?

**Comment by tankbusta** [comment]
Good point @awhite456 - To summarize

1. Constraints remain the same
2. Drop `reg_value_result`
3. Create `reg_value_before` which would indicate the previous key/value before the mutation

**Comment by pagbabian-splunk** [comment]
This was one of the suggestions from the Slack thread as I recall (I may have made it myself in fact).  @tankbusta added a constraint and some clarification that will be useful in documentation without changing attribute names (or meanings).  If we want a more surgical approach, then I would change the name of `reg_key_result` and `reg_value_result` to `reg_key_prev` as Optional and `reg_value_prev` as Optional, and only populate them in the Modify case.

In these cases, `reg_key` and `reg_value` would remain Required, as they MUST always be there for any operation.

I don't know how we constrain `reg_key_prev` and `reg_value_prev` to be populated for Modify but it's not clear the previous value will always be available so it may just be Optional.
