### ISSUE TITLE
Managed Entity object needs an enum list of object types

### ISSUE THREAD

**Issue by pagbabian-splunk** [ocsf/ocsf-schema#396]
managed_entity `type` is a String without any guidance for how to populate the value.  It should use the same approach as observable, where type_id/type combination has the normal enum conventions.
The `type_id` should include User, File, Hostname, Email etc.  In fact, it might be able to share the same enum values as observable (e.g. Endpoint, Process Name, URL, Container etc.)

**Comment by rroupski** [comment]
The Managed Entity object is used in the Entity Management event class (for MDR updates), so the type could be anything.

**Comment by rroupski** [comment]
@pagbabian-splunk since the values of the type are known, is it OK to have only a `type` attribute?

**Comment by pagbabian-splunk** [comment]
Yes I think that's what I'm thinking. Similar to the Observable object. We still have Other too which would be equivalent to what we have now

**Comment by k2niner** [comment]
Some items for consideration: Document, File, Folder, Object, Webpage, Other. Would like to cover use cases where access to these types of objects are security relevant events (classified objects, health data, etc).

**Comment by k2niner** [comment]
I put a proposal in to modify `Resource` Object. The enum list was a bit of a "off the cuff" marriage the existing `Resource` plus my sponsor's enum list. Having now looked at `Observable`, we could consider using that enum list but it would need to be augmented.

**Comment by pagbabian-splunk** [comment]
This is a good idea - as per our discussions in Slack.  Resource can also describe Managed Entities but it also needs specific enum values along with Other for its `type_id`.  `Observable` and `Resource` may overlap, but `Observable` is intended to surface attribute values from within an instance of a class so they are found in one place no matter the event structure.  The lists could be reflective of each other.

**Comment by pagbabian-splunk** [comment]
Not sure where we are on this now as there have been many related discussions and changes.

@k2niner do you have a modified `resource_type_id` enum list as an augmented `Observable` enum list?  The attribute is starting to be reused (e.g. in the URL object).

**Comment by rroupski** [comment]
N/A anymore
