### ISSUE TITLE
Change 'parent_folder' attribute in 'File' object to 'folder' & make it a 'File' object

### ISSUE THREAD

**Issue by mr-splunk** [ocsf/ocsf-schema#403]
The File object 'describes files, folders, links and mounts, including the reputation information, if applicable.'

<img width="476" alt="image" src="https://user-images.githubusercontent.com/91983279/207457951-949b358c-2f27-4bf7-a22f-b6af1bcd6efc.png">

Currently, this object has an attribute called `parent_folder`, which represents 'the folder in which the file resides'.

<img width="944" alt="image" src="https://user-images.githubusercontent.com/91983279/207457894-9b2cb051-e92f-466a-8352-f3c64acc6285.png">

By the definition above, this attribute should be a `file` object, named `folder`.

**Comment by tankbusta** [comment]
Similar to the Process Object in `Process Activity`, we may want to include verbiage similar to this in the description 

> It is recommended to only populate this field for the first parent object, to prevent deep nesting.

**Comment by mr-splunk** [comment]
> Similar to the Process Object in `Process Activity`, we may want to include verbiage similar to this in the description
> 
> > It is recommended to only populate this field for the first parent object, to prevent deep nesting.

Good suggestion, makes sense to me. I have no objections to it :)

**Comment by jp-harvey** [comment]
This makes sense to me too. This is another use case for having an option to include either an ID or an observable (to allow more advanced relational platforms to save on data volumes and automatically prevent deep nesting).
