### ISSUE TITLE
Promote Email Activity Class from dev extension to main

### ISSUE THREAD

**Issue by ablyler** [ocsf/ocsf-schema#418]
Promote the base `email_activity` class from the `dev` extension to the `main` branch.

Note: this does not include the `email_file_activity` nor the `email_url_activity` classes.

**Comment by rroupski** [comment]
I think we should also move `email_file_activity` and `email_url_activity` classes. They will be useful for reporting email file attachments and url's.

**Comment by ablyler** [comment]
@rroupski I was hesitant to move those classes based on the feedback from @pagbabian-splunk in slack. Also, the Barracuda solutions will not be utilizing the `email_file_activity` and `email_url_activity` classes in the near term. I suggest waiting to bring them over until we have someone interested in utilizing them.
