### ISSUE TITLE
Proposal: Start enumeration values at 0

### ISSUE THREAD

**Issue by Jthomas54** [ocsf/ocsf-schema#422]
It isn't uncommon that IDL's do not support setting the value of enumerations, [Protocol Buffers](https://developers.google.com/protocol-buffers/docs/proto3#enum) being one of them.  In these cases, enumerations start at 0 and increment from there.

I am proposing that enumerations start at `0` and increment by one from there. `0`  should always represent an `Unknown` value while `1` should represent `Other`, where applicable.

```
Unknown = 0,
Other = 1,
// Class specific/reserved enumerations
```

**Comment by paveljos** [comment]
Discussed on the 1/17/2023 call. Initial feedback is supportive; we will leave this open to catch any additional feedback in the meanwhile.

**Comment by rroupski** [comment]
We could change the value of **Other** as `255`, and then we don't have to renumber the enum values. Note, it adds a minor limitation -- the enum values must in the range of 1-254, which is probably good enough for any practical purpose.

**Comment by rroupski** [comment]
@Jthomas54 please note that OCSF schema also support string based enum values, which may not be supported by some IDL's.

**Comment by Jthomas54** [comment]
@rroupski In what classes are strings used over numeric types for enumerations?

**Comment by rroupski** [comment]
The string enum values are usually used when the values are defined by external standard. For example, see the values of the depth attribute in the the [cvss](https://schema.ocsf.io/objects/cvss) object.

**Comment by pagbabian-splunk** [comment]
Although the DMTF convention from where we derived the Unknown and Other would have been 0, 1, and then the specific values.  If we don't want to change the specific values at this juncture, have them bookended by 0 for Unknown and 255 for Other would only break people that are using -1 for Other, and obviate the need to renumber every enum.  If this is acceptable it is the least disruptive, to solve @Jthomas54 issue.  I'm ok with that, but if we want to go to 0, 1 like DMTF, raise your voices now !!!

**Comment by pagbabian-splunk** [comment]
Per this morning's call, we agreed to 'bookend' the enums with 0 = Unknown and 99 = Other.  This also limits how many distinct enum values to 98 within the bookends.  It could extend past 99 but would not be desirable.

**Comment by rroupski** [comment]
done, see PR #436
