### ISSUE TITLE
Rename Malware Profile to Security Profile

### ISSUE THREAD

**Issue by Aniak5** [ocsf/ocsf-schema#430]
We discussed renaming the `malware` profile to `security` so that this profile is more generic and can be used by events which contain security related dispositions. Alter the requirement for the `malware` attribute within the profile to be `optional`. This allows classes to have all security related information in one profile even when it's not necessarily malware.

**Comment by pagbabian-splunk** [comment]
As per our discussion this morning, I suggest we name the profile `Security Controls` and it can be a distinct profile, rather than a rename.

**Comment by Aniak5** [comment]
@pagbabian-splunk `Security Controls` sounds like a good name. It makes sense to use `disposition_id` given that it aligns well with security control: 
`"When security issues, such as malware or policy violations, are detected and possibly corrected, then disposition_id describes the action taken by the security product."` 

My only concern with creating a new profile is that these two profiles will be very similar which might cause some confusion.
