### ISSUE TITLE
Create new OS Resource Object for Resource Activity

### ISSUE THREAD

**Issue by awhite456** [ocsf/ocsf-schema#432]
The current [Resource Object](https://schema.ocsf.io/objects/resource) is used by a variety of classes. For the majority of these, they focus on a cloud or on-prem resource, such as an S3 bucket or fileserver, and the current iteration of the class suits this purpose well.

For the System Activity class [Resource Activity](https://schema.ocsf.io/classes/resource_activity) however, the changes made to the resource object stray from the Operating System Resource (such as a mutex or timer) that this resource object originally defined. Recommended fields, such as `owner` and `group name` do not apply to OS Resources, as do many of the optional fields, such as `cloud partition` and `region`. This can become confusing for end users when attempting to map or use `Resource Activity` events, as the context-specific definition of a `resource` is lost.

To solve this problem, a new object named `Operating System Resource` is needed, to better model OS resources and provide disambiguation to end users. This would additionally allow the fixed set of resource types (although [numerous on Windows](https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4663)) to be defined as an enumeration to make it clear what this object represents and ensure a clear, consistent mapping of events.

**Comment by rroupski** [comment]
Done, see PR #433
