### ISSUE TITLE
String Sibling Normalization

### ISSUE THREAD

**Issue by paveljos** [ocsf/ocsf-schema#449]
"sibling" strings, e.g, `severity` as it relates to `severity_id`, are currently defined as relating to the event source.  Again, for severity, "The event severity, as defined by the event source."

This has a few potential problems:
1. Inconsistency with how OCSF defines the utilization of `ref_` fields; i.e., `severity` should be renamed `ref_severity`
2. No offer of normalization for applications that utilize or prefer the strings for things like captions or visualizations. e.g, `Informational` and `informational` and `INFORMATIONAL` may be grouped independently for poorly written queries.
3. Cases that do not fit into the pre-defined categorization get lumped into "Other" with no further assistance offered by the schema for data taxonomy.

I would recommend the following:
For "sibling" fields, the should be understood and defined as enum+. The strings will match the predefined cases as defined by the OCSF definition for their integer sibling, with the exception of "Other", where the original value is preserved and offers data consumers an opportunity to further understand and utilize the data. 

For example, 
```
severity:
0	Unknown
1	Informational	
2	Low	
3	Medium	
4	High	
5	Critical	
6	Fatal	
99	Other
```
If someone had the severity as "Blocker", the int enum `severity_id` would be `99` and the string sibling `severity` would be `Other:Blocker`

I will set up a poll for voting and additional feedback.

**Comment by paveljos** [comment]
https://github.com/ocsf/ocsf-schema/discussions/450

**Comment by floydtree** [comment]
+1.
We should definitely settle on this prior to RC. I like the proposed idea. We’ll also need to update the descriptions of all the sibling fields.
For the grammar convention portion, currently it seems we have space separated camel case, which might not be ideal. Perhaps restrict it to a single word? Or go with proper CamelCase without a space. (Considering this a value and not a field name, we don’t have to stick to underscore convention)
