### ISSUE TITLE
Cloud Profile on the Base Class ??

### ISSUE THREAD

**Issue by pagbabian-splunk** [ocsf/ocsf-schema#457]
I noticed that the Cloud profile has been added to the Base event class.  Under what circumstances would it be applied to every event class when it is also applied to specific event classes?

**Comment by floydtree** [comment]
This change was pushed a few months ago I believe. `cloud` profile is not applied to specific event classes, it's only in the base event.

The reason being, logs in every event class that we have today or will have in future can be from cloud hosted system, hence  would require an object to store cloud attributes.(account_id, region, partition, provider etc).

For example, **any** system activity class can be used to map events emitted by a Windows system running on an EC2 instance in the cloud, the same goes for Network Activity classes, configuration/inventory classes, the upcoming Storage classes, so on and so forth.

Thus the idea to make cloud profile available in all the classes, and the simplest method of doing that is add it in the base_event, which every other class extends. Similar idea was used for the `datetime` profile.

Hope this helps.
