### ISSUE TITLE
Identity, IdP, and User

### ISSUE THREAD

**Issue by pagbabian-splunk** [ocsf/ocsf-schema#458]
We need to have a clear explanation of these objects, and when and how they are used in event classes, such as Auth Activity or Account Change.  This is how I understand things but I also have questions:

- An Identity Provider issues Identities, which in turn act as security principals when authenticating
- Therefore, they are paired: When an IdP logs activity to the Auth Activity or Account Change classes, it does so in the context of the Identity that has authenticated or whose account has changed
- User holds much of the information of the Identity, and has much of the Identity information: e.g. username (i.e. the security principal), session_uid, session_uuid, uuid, uid - seems like a bit of a hodge-podge, especially when we also have Identity that has a Session.uid attribute, redundant with User's session_uid.
- I don't know where `mfa` went (seems like it should be part of the Session? but it's also a state variable for the Identity that is paired with a particular IdP)
- The IdP object seems a bit thin, but maybe logs don't tell us much

We should carefully look at User, and Identity and understand their usage across the schema.  E.g. Identity seems to have `invoked_by` and `message` (which is also in the base class) that I don't fully understand.

**Comment by floydtree** [comment]
> An Identity Provider issues Identities, which in turn act as security principals when authenticating. 

That's correct.

> Therefore, they are paired: When an IdP logs activity to the Auth Activity or Account Change classes, it does so in the context of the Identity that has authenticated or whose account has changed

Not necessarily, for example in case of AWS IAM, IAM logs the activity, however IDP can be an entity external to IAM. Therefore, would be important to log who was the IDP, thus `idp` is added as an object inside the contextual object `identity` which is the source of the activity. To help put perspective, in case of an account_change, the question identity object will answer is WHO changed the account? 

> I don't know where mfa went (seems like it should be part of the Session? but it's also a state variable for the Identity that is paired with a particular IdP)

It is a part of the session object - https://schema.ocsf.io/objects/session

> User holds much of the information of the Identity, and has much of the Identity information: e.g. username (i.e. the security principal), session_uid, session_uuid, uuid, uid - seems like a bit of a hodge-podge, especially when we also have Identity that has a Session.uid attribute, redundant with User's session_uid.

User object is indeed at the core of Identity, user/role details will be accounted for via this object. I didn't notice the session_uid/uuid fields in that object, might be new. The descriptions make it sound like these fields were added for `Windows specific usecases`. 
I am in favor of the current `session` object to be modified to add these fields as optional, wouldn't want to crowd the user object with too many fields. We'll need to add `uuid` in the session object then both `session_uid, session_uuid` can be removed from the user object. - $AI1


> The IdP object seems a bit thin, but maybe logs don't tell us much

That's correct, at least in the log sources that I have used for this object. Attributes can be added as necessary, if a valid gap is identified with log data.

> invoked_by & message
* A service that invoked an activity on behalf of a user. In case of authentication and account change, this field will likely be not applicable. But these are not the only two classes the make use `identity` object. The description in the object appears to be clear, but we can update if need be. 
* I agree with your point about `message`, this field can be removed from identity - $AI2
