### ISSUE TITLE
DNS Question as an array

### ISSUE THREAD

**Issue by mosajjal** [ocsf/ocsf-schema#465]
in the [RFC](https://www.rfc-editor.org/rfc/rfc1035#section-4.1.2), DNS Question is not mandated to have only one entry. In fact, there are some attacks that leverage multi-question DNS packets as a C2 vector.

I propose changing the spec to allow for an array of DNS Queries rather than a single Query object.

**Comment by pagbabian-splunk** [comment]
Interesting. I think you are suggesting that rather than having a `query` attribute of DNS Query type, we would have `queries` for an array of DNS Query.  We have `answers` for an array of DNS Answer.

I would also point out that the attribute name `query` or `queries` is very generic, and in the future there may be other types of queries that are not related to DNS.

**Comment by mosajjal** [comment]
> Interesting. I think you are suggesting that rather than having a `query` attribute of DNS Query type, we would have `queries` for an array of DNS Query. We have `answers` for an array of DNS Answer.

that's correct. 

> I would also point out that the attribute name `query` or `queries` is very generic, and in the future there may be other types of queries that are not related to DNS.

if we want to be thorough, no matter the answer or the question, each DNS entry is a "resource type". so Ideally we'd have to shift from query and answer being different types to a new "RR" type defined as per [4.1.3](https://www.rfc-editor.org/rfc/rfc1035#section-4.1.3) and both queries and answers would be an array of RRs.

**Comment by pagbabian-splunk** [comment]
Given this would be a breaking change to the DNS Activity class, I would suggest adding this as a Proposal in Discussions.

**Comment by Aniak5** [comment]
If the request in the log has multiple queries then the mapper should produce multiple events instead of one.
