### ISSUE TITLE
Extension labeling and versioning in Metadata

### ISSUE THREAD

**Issue by rroupski** [ocsf/ocsf-schema#493]
### Discussed in https://github.com/ocsf/ocsf-schema/discussions/477

<div type='discussions-op-text'>

<sup>Originally posted by **pagbabian-splunk** February  6, 2023</sup>
There is no way within an event to determine whether an extension is part of the event, unless the extension is a net-new event class (or possibly Profile etc) with new names that indicate who has extended the schema.  For example, Splunk had a Network File Activity extension class, and a Detection Report extension class which would not have been obvious as to who extended the schema.  Even with a descriptive name indicating the extender, there may be more than one version of the extension.

At the expense of further bloat of the event, I'm suggesting that Metadata more explicitly have a place to indicate the producer or consumer that has extended that portion of the schema, and their version.  The version may in fact be more important than the vendor, since just an event name with vendor prefix, for example, would not convey what version.</div>

**Comment by rroupski** [comment]
Add Extension object with the following attributes:
```json5
{
  uid: string_t,    // the extension uid is defined as a number ?
  name: string_t,   // for example: "dev"
  version: string_t // for example: "1.0.0-alpha.2"
}
```

**Comment by pagbabian-splunk** [comment]
Looks good to me.  This would accompany a new attribute, e.g. `ext` or `extension` of type Extension within the Metadata object.
