### ISSUE TITLE
Should string siblings be required fields?

### ISSUE THREAD

**Issue by johan1252** [ocsf/ocsf-schema#529]
Follow up to discussion in https://github.com/ocsf/ocsf-schema/discussions/450 for which string siblings were originally discussed.

In https://github.com/ocsf/ocsf-schema/pull/459 string sibling descriptions and purpose has been changed.
Now every id (ex: `severity_id`) should have an available string version (`severity`).

As mentioned by @pagbabian-splunk:
> One more point- the above proposal didn't make mention of whether the enum label is required in the sibling or whether it is optional. The siblings themselves are all marked as Optional, but would effectively be silently promoted to Required if Other was the enum value.

Could string sibling fields be required so that consumers can rely on them being present?

**Comment by rroupski** [comment]
Some time ago, we made the sibling attributes having the same requirement as the enum attributes, however to keep the data size small we decided to revert that change and make all siblings optional.
