### ISSUE TITLE
HTTP Activity IDs and HTTP Method 

### ISSUE THREAD

**Issue by mr-splunk** [ocsf/ocsf-schema#537]
HTTP `activity_id` enums should follow request methods: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

<img width="104" alt="image" src="https://user-images.githubusercontent.com/91983279/227017448-326148df-f5d0-4622-902a-f4ecc51fde37.png">

The `http_request` object has an `http_method`, which should be an enum of valid HTTP methods.

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/91983279/227052819-426af696-6159-411c-bb4a-6aca7d3eae6c.png">

**Comment by rroupski** [comment]
done
