### ISSUE TITLE
Vulnerability object definition limited to CVE framework.

### ISSUE THREAD

**Issue by Apocrathia** [ocsf/ocsf-schema#538]
[Vulnerability objects are locked to the CVE framework.](https://github.com/ocsf/ocsf-schema/blob/7d4424c9dc9bde85b9e6cb6016341fd3be68b2ad/objects/vulnerability.json#LL7C8-L7C8)

Could this be changed to a basic identifier? The dependency on having an assigned CVE means that any vulnerabilities that don't have an associated CVE (such as CWEs), have no way of being represented by this object.

**Comment by rroupski** [comment]
Yes, it makes sense to add CWE object and add it to the vulnerability object:

```json
{
  "description": "The vulnerability object describes details related to the observed vulnerability",
  "caption": "Vulnerability Details",
  "name": "vulnerability",
  "extends": "object",
  "attributes": {
    "cve": {
      "requirement": "recommended"
    },
    "cwe": {
      "requirement": "recommended"
    },
```

**Comment by Apocrathia** [comment]
Renaming the CVE field would enable the usage of either a CVE or CWE object interchangeably. 
```json
{
  "description": "The vulnerability object describes details related to the observed vulnerability",
  "caption": "Vulnerability Details",
  "name": "vulnerability",
  "extends": "object",
  "attributes": {
    "identifier": {
      "requirement": "required"
    },
```
Where 'identifier' could reference either a CWE or CVE option. However, that will probably break existing integrations that rely on the existing data pattern.

As for the CWE object itself, I will go ahead and fork the schema to work on the definition.

**Comment by Apocrathia** [comment]
Rudimentary definition built out. Here's the summary:
- Removed CWE references from CVE object, as this is something that is already externally defined by MITRE and can be retrieved from them.
- Added basic CWE object. Only includes the `uid` field for right now. Can be used to derive URLs.
- Add CWE field to Vulnerability object. Change CVE/CWE to recommended.
https://github.com/ocsf/ocsf-schema/compare/main...Apocrathia:ocsf-schema:issue-538

**Comment by rroupski** [comment]
> Where 'identifier' could reference either a CWE or CVE option. However, that will probably break existing integrations that rely on the existing data pattern.

The CWE and CVE are different objects, right? If yes, then this will not work.

**Comment by rroupski** [comment]
> * Added basic CWE object. Only includes the `uid` field for right now. Can be used to derive URLs.
> * Add CWE field to Vulnerability object. Change CVE/CWE to recommended.

we should add the `cwe_url` to the `cwe` object, so we can have the same attributes as defined in the existing `cve` object.

**Comment by irakledibm** [comment]
CWE is already part of the CVE object. CWE by itself is not a vulnerability.

**Comment by Apocrathia** [comment]
> CWE is already part of the CVE object. CWE by itself is not a vulnerability.

I have to disagree with you. A CWE is a vulnerable pattern, whereas a CVE is simply a _reported_ vulnerability. As previously mentioned, if you're working in an environment where you're building software, you won't have CVEs for the weaknesses identified in your software that may or may not have been released to the public. However, they're still valid vulnerabilities that need to be remediated.

Additionally, while every finding may not have a CVE attached to it, every CVE will have a CWE referenced. By splitting CWE into a separate object, we can enable a broader utilization of the OCSF schema in organizations that don't utilize software that has been publicly released and may not be applicable to being granted a CVE in the first place.

**Comment by Apocrathia** [comment]
> > * Added basic CWE object. Only includes the `uid` field for right now. Can be used to derive URLs.
> > * Add CWE field to Vulnerability object. Change CVE/CWE to recommended.
> 
> we should add the `cwe_url` to the `cwe` object, so we can have the same attributes as defined in the existing `cve` object.

[Done}(https://github.com/Apocrathia/ocsf-schema/commit/7f0624c742cd04a604a809d217b53b2746799210)

Once this looks acceptable, I can submit a PR containing the changes. Just let me know what you need me to do.

**Comment by irakledibm** [comment]
Looks good to me
