### ISSUE TITLE
Clear up ambiguity of the http_request.prefix attribute

### ISSUE THREAD

**Issue by pagbabian-splunk** [ocsf/ocsf-schema#565]
`http_request.prefix` description today is "Domain prefix."  It is intended to be the subdomain portion of a URL or FQDN.  The description should be more explicit.  Ideally, `prefix` would be `subdomain` which would be a breaking change.  At minimum, we need a PR to update the description (non-breaking).

A better description:
The subdomain portion of the URL. For example: <code>sub</code> in <code>https://sub.example.com</code> or <code>sub2.sub1</code> in <code>https://sub2.sub1.example.com</code>

**Comment by rroupski** [comment]
What is the relation of `http_request.url.hostname` and `http_request.prefix`? They sound similar to me.

**Comment by rroupski** [comment]
done
