### ISSUE TITLE
The data dictionary path_t regex is broken

### ISSUE THREAD

**Issue by mtharp0** [ocsf/ocsf-schema#618]
The existing regex is: `^[\pL0-9_]+[\pL0-9 ~!@#%&*\-./_]*$`
However, there could be a leading `/` or a `\`. Here is a potential solution: `^[\/]?[\p{L}0-9_]+[\p{L}0-9 ~!@#%&*.\/\\_-]*$`

**Comment by rroupski** [comment]
@mtharp0 should we replace the regex with `^[\/]?[\p{L}0-9_]+[\p{L}0-9 ~!@#%&*.\/\\_-]*$`? I can create a pull request for it?

**Comment by mtharp0** [comment]
I think it makes sense to remove the regex entirely and just make them stings. I.e. eliminate the file_name_t and path_t
