### ISSUE TITLE
User object only captures username data, not full name data

### ISSUE THREAD

**Issue by sfriedfertig** [ocsf/ocsf-schema#649]
The User observable object has caption `name` which is described as a username (e.g. `john_doe`), but does not have a caption for capturing an actual name (e.g. John Doe). Perhaps `name` can be renamed to `username`; alternatively, for backwards compatibility, a new caption such as `full_name` can be included. While small, this change should make it one step easier to associate a username with an actual human.

**Comment by pagbabian-splunk** [comment]
I will create a PR to add a new optional attribute, `full_name` but not change `name` to `username` as that will have ripple effects, since all entities have `name`, and it will be an unnecessary breaking change.
