### ISSUE TITLE
Tracking differences between releases

### ISSUE THREAD

**Issue by jp-harvey** [ocsf/ocsf-schema#665]
It was raised in the weekly call that folks were asking what were the differences between releases.

**Comment by jp-harvey** [comment]
Github has a way of generating release notes automatically between releases. This is done by default using the PR descriptions, and can be made more sophisticated through the use of tagging.

Need to:
- Determine the MVP for our release notes
- Update the contributing guide with the relevant information about how this is done and any associated guidelines

**Comment by floydtree** [comment]
Yep, good to close

**Comment by mikeradka** [comment]
This was taken care of via our CHANGELOG process in `1.2.0`.
