### ISSUE TITLE
Add Destination Endpoint to Network File Activity Class

### ISSUE THREAD

**Issue by Aniak5** [ocsf/ocsf-schema#672]
Currently the network file activity class only has a `src_endpoint` and does not have a `dst_endpoint`. Add a destination endpoint attribute to the event class. Here is an example of a log from Cisco FTD provided by Omri which requires the dst endpoint:
```
2023-02-01T04:03:28Z ftd : 
%FTD-1-430004:                                          //  File events
 DeviceUUID: a8af1240-4829-11ec-b62a-af3eff1734bd,
 InstanceID: 5,
 FirstPacketSecond: 2023-02-01T04:03:27Z,
 ConnectionID: 31400,
 SrcIP: 10.180.10.10,
 DstIP: 69.164.0.128,
 SrcPort: 51853,
 DstPort: 80,
 Protocol: tcp,
 FileDirection: Download,
 FileAction: Malware Cloud Lookup,
 FileSHA256: e96fd03925d8c80bc4d7cf31c6b0b7ac8346b1d4fe74ffd839702e1d654dd146,
 SHA_Disposition: Unavailable,
 SperoDisposition: Spero detection not performed on file,
 FileName: am_delta_patch_1.381.2975.0_eb89249a0cef3f863823bb996d726c2b5ce99015.exe,
 FileType: MSEXE,
 FileSize: 415192,
 ApplicationProtocol: HTTP,
 Client: Web browser,
 WebApplication: Microsoft Update,
 User: Not Found,
 FilePolicy: Microsoft Update,
 FileStorageStatus: Not Stored (Disposition Was Pending),
 FileSandboxStatus: Sent for Analysis,
 FileStaticAnalysisStatus: Failed to Send,
 URI: /d/msdownload/update/software/defu/2023/02/am_delta_patch_1.381.2975.0_eb89249a0cef3f863823bb996d726c2b5ce99015.exe,
 IngressVRF: Global,
 EgressVRF: Global
```

Related to https://github.com/ocsf/ocsf-schema/discussions/671 discussion.

**Comment by rroupski** [comment]
This example looks like an HTTP activity with a file (with the security control profile)?

**Comment by Aniak5** [comment]
Yes it does look like HTTP activity. Yup @rroupski, it seems as if we would have to add http attributes and also apply the security control profile on top of the destination endpoint.

**Comment by mr-splunk** [comment]
Today's scope of the `Network File Activity` class is specifically geared towards cloud file storage services: `Network File Activity events report activities on a cloud file storage service such as Box, MS OneDrive, or Google Drive.` 

This raises an interesting point - this Cisco FTD event contains the key elements of 1. networking and 2. file activity.

That said, `Cisco FTD` is more of a Firewall with IDS/IPS capabilities, rather than a cloud file storage service.

According to ChatGPT, Cisco Firewall Threat Defense:

> It combines the capabilities of firewall and intrusion prevention systems (IPS) with advanced threat detection and mitigation features.

The Cisco FTD event [`FTD-1-430004`](https://www.cisco.com/c/en/us/td/docs/security/firepower/Syslogs/b_fptd_syslog_guide/syslogs4.html#id_89132) identifies a file event via the network firewall, but unrelated to a cloud file storage service.

<img width="715" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/91983279/4914ca3e-b160-450c-9a84-eecc904924a8">

---
There are a few options I see:
1. Roumen's suggestion of mapping this event to HTTP activity with a file.
     1. **Advantage**: We would not have to broaden the `Network File Activity` class. Broadening a class could cause bloat and ambiguity.
     2. **Disadvantage**: we would lose the `activity_id` enums related to `Network File Activity`, such as `Download`
1. We could broaden the scope of the `Network File Activity` class, and add `dst_endpoint` and the `Security Control` profile with http attributes.
    1. **Advantage**: We would keep the `activity_id` enums related to `Network File Activity`, such as `Download`.
    1. **Disadvantage**: In order to map this Cisco FTD event to the Network File Activity class, the tradeoff would be that we would have to change the scope of the Network File Activity class to more broadly include both scenarios (cloud file storage services AND firewall ids/ips).
    2. **Disadvantage**: Adding the Security Control profile and http attributes may again introduce confusion and ambuity to this class.

1. There is currently no event class for Deep Packet Inspection events such as `IDS/IPS`. We could consider creating one.
    1. **Advantage**: WAF also encompasses Deep Packet Inspection. If constructed properly, such a class could potentially cover IDS, IPS and WAF under the umbrella of Deep Packet Inspection events. We also have a [proposal currently for a WAF class](https://github.com/ocsf/ocsf-schema/discussions/671).
    3. **Disadvantage**: More work? Is another OCSF Class too much? Does this belong in the Findings category, or a different category?

**Comment by rroupski** [comment]
This is a good example of a complex event – an event that reports multiple "activities". The event was created by a security product, a firewall, based on a file initiated by a device/user activity:
1. Device (10.180.10.10) downloaded or attempted to download a file. What actually happened is a bit unclear -- I think the file is not [yet] downloaded: _FileStorageStatus: **Not Stored**_
2. Based on the file download activity, the firewall triggered and reported some other/related activities: _FileAction: **Malware Cloud Lookup**_ and _FileSandboxStatus: **Sent for Analysis**_.

(1) (a) the main activity/activity_id, that's the activity that triggered the event, is file download. Therefore, we must have a file object as a `primary`, required attribute. I also see a User, which seems to be a good candidate for another `primary` attribute.
(b) There are a few attributes that help to understand how the file was downloaded, such as the connection information, which I consider as an event `context`.
I don't think the OCSF schema currently defines an event class that can correctly describe the above, so this is the first issue that we should address.

(2) The event also reports the actions executed by the firewall. For that, we need a profile (or maybe even two profiles), which we can apply on the "file download" event. And this is the second issue that we should address.

**Comment by Aniak5** [comment]
I really like the idea of creating a firewall profile. It is also important to the event above to have file specific activities such as `download`. It seems like we should leverage the existing network file activity event and add the `dst_endpoint` attribute. With this approach we are still missing some of the connection and http related information present in the log above. We cannot extend the network or http event classes because they both require the `src_endpoint` and the `dst_endpoint` attributes. This brings me back to an issue we had a long time ago about creating a network profile. Though it seems redundant to apply a network profile to an event class within the network category.
