### ISSUE TITLE
Timestamp formats

### ISSUE THREAD

**Issue by jp-harvey** [ocsf/ocsf-schema#747]
We've had a lot of discussion previously about timestamps, and we arrived at a nice clean simple solution which was to have the millisecond epoch time as the `time` in the base attribute.

We've found that when working with OCSF data there are destination systems that support only a specific timestamp format. Most recently it's been Opensearch, which supports an ISO timestamp.

When putting OCSF data in to a system that can't accommodate the OCSF epoch format the options are:

1. Put it in as OCSF formatted data and don't index a timestamp at all (obviously not entirely useful for timeseries data)
2. Accept that the storage format and the transmission format will be different and process the timestamp before it hits Opensearch replacing the millisecond epoch timestamp with the ISO string timestamp that Opensearch is able to index. If the data needs to be exported, transform the ISO format back to the OCSF conforming epoch format.
3. Put the ISO format in `unmapped` and index on that, leaving the storage format OCSF compliant

The way we have tackled it is by option 3, putting a `timestamp_iso` field in `unmapped` so that we can store the data in an OCSF compliant way, and then don't need to do additional transformations on input and output from the system.

While the prompt for this is a storage format issue, the same problem could arise in other cases such as where a higher precision timestamp is needed.

The solution we've chosen in this case works great but feels a bit hacky for timeseries data, and am curious if others have encountered this issue and how they have worked with it / around it.

OCSF has many more real-world use cases than it did when we implemented timestamps. Would now be a good time to discuss how we could accommodate additional timestamp formats in a more "first class" way?

**Comment by floydtree** [comment]
Have you taken a look at the datetime profile? The issue you described was pretty much the problem this profile intends to solve.
It adds a *_dt field(with a datetime_t format) for every timestamp field in a class where the profile is applied.

**Comment by jp-harvey** [comment]
How did I not remember that? I've looked at those profiles 1000 times! :man_facepalming:

Certainly takes care of both use cases described, thanks @floydtree
