### ISSUE TITLE
RFC3339 date/time format regex issues in OCSF datetime_t type validation

### ISSUE THREAD

**Issue by jp-harvey** [ocsf/ocsf-schema#752]
The regex for `datetime_t` validation is as follows:
```
^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}%3A\d{2}(?:.\d+)?[A-Z]?(?:[.-](?:08:\d{2}|\d{2}[A-Z]))?$
```
This regex appears to have the following issues:
- The `%3A` and `:08` mean no ISO formatted timestamp will validate
- The fractions of seconds section will not cause a valid RFC3339 datetime to fail, but matches on "any character, plus any number of digits", instead of "a decimal point, plus any number of digits", so will validate non-conforming formats
- The first `[A-Z]?` will not cause the regex to fail validation for a conforming RFC3339 timestamp, but is extraneous and does not represent a part of RFC3339 so will validate some non-conforming timestamps.
- The timezone regex passes validation for valid RFC3339 timestamps but will also validate some invalid timestamps due to `[.-]` and `[A-Z]`

**Comment by rroupski** [comment]
Done, see PR #753
