### ISSUE TITLE
ATTACK/Tactic/Technique Object Sub-techniques, Link & Requirements

### ISSUE THREAD

**Issue by acockburn** [ocsf/ocsf-schema#760]
1. The ATTACK object description should make it clear that the **technique** field can also be used to indicate a **sub-technique** as well. This comes down to an additional index on the technique field, e.g.:

Technique: T1059
Sub-technique: T1059.003

Either should be allowed, and the description should reflect this.

2. It would be good practice to allow tools generating the alert to provide a mapping directly back to the ATT&CK matrix via a URL. Since both Techniques, Sub-techniques and Tactics have their own entries, ti would seem best to include the URL in the Tactic and Technique sub-objects. This should be optional, and the description should note that if a link is supplied, it MUST be the *version permalink* supplied be the Mitre description at the time the alert was issued rather than just the URL of the page navigated to via a browser. This ensures that the description and information linked to on the Mitre site is immutable.

In addition, this to a large extent removes the need for the MITRE version number so we should consider deprecating this field as a result of the URL additions.

3. In the ATTACK object, Tactic and Technique should be optional, as they may not both be known.

**Comment by zschmerber** [comment]
Seems like having a sub object array for Tactic is a pain to map as well. Feels like the Attack object can be flattened seem example below. If a part of the array is null because id dose not exists all available  info is displayed.

"attacks": [
		{
			"tactics_name": "Reconnaissance",
			"tactics_uid": "TA0043",
			"technique_name": "Active Scanning"
                         "technique_uid": "T1595"
                         "sub_technique_name": "Scanning IP Blocks"
                         "sub_technique_uid": "T1595.001"
                          
		}
	],

**Comment by floydtree** [comment]
Taking @acockburn's note into account and considering the existing objects that we have today, we can have an object similar to the following - 

```
{
  "caption": "Attack",
  "name": "attack",
  "description": "The Attack object describes the technique and associated tactics related to an attack. See <a target='_blank' href='https://attack.mitre.org'>MITRE ATT&CK®</a>.",
  "extends": "object",
  "attributes": {
    "tactics": {
      "requirement": "optional"
    },
    "technique": {
      "requirement": "optional"
    },
    "sub_technique": {
      "requirement": "optional"
    },
    "version": {
      "requirement": "recommended"
    }
  },
  "constraints": {
    "at_least_one": [
      "tactic",
      "technique",
      "sub_technique"
    ]
  }
}

```

In each sub object we can add an optional `src_url` to allow folks to populate the permalink to the matrix.

```
"attacks": [ 
                {
			"tactic": {
				"name": "Reconnaissance",
				"uid": "TA0043",
                                  "src_url": "Permalink to the tactic"
			},
			"technique": {
				"name": "Active Scanning",
				"uid": "T1595",
                                 "src_url": "Permalink to the technique"
			},
			"sub_technique": {
				"name": "Scanning IP Blocks",
				"uid": "T1595.001",
                                 "src_url": "Permalink to the subtechnique"
			},
                         "version": "The attack matrix version"
		}
]

```

**Comment by mikeradka** [comment]
<img width="760" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/91983279/4271da0c-0a42-47b9-9c32-f8aac1d98652">

Something we discussed, `version` is not always available in an event. `Required` could possibly be too strict.

**Comment by floydtree** [comment]
Changes are now merged!
