### ISSUE TITLE
Path to app/schema and documentation is also not updated.

### ISSUE THREAD

**Issue by mranv** [ocsf/ocsf-schema#781]
`docker run -it --rm --volume /path/to/ocsf-schema:/app/schema -p 8080:8080 -p 8443:8443 ocsf-server `

**Change the path/to to your local OCSF schema directory (use an absolute path). Note, the -p 8443:8443 parameter enables HTTPS with a self-signed SSL certificate.**

The repo of schema doesn't contain folders and files like /path/to/ocsf-schema:/app/schema

**Comment by rmouritzen-splunk** [comment]
The `ocsf-server` repo's `README.md` was updated with an example `docker run` with an example replacement of `/path/to`.

About the SSL certificate, please note that the self-signed certificate is not actually used in the actual `https://schema.ocsf.io` server. This server fronts the service with Nginx, and Nginx is handling the SSL with a properly signed certificate.

If you'd like to host your fork of the OCSF server, either want to do the same, or if you want to have the underlying Erlang VM handle SSL, you'll need to dig in to how the Phoenix web server configuration gets passed the certificate details. This may require a change to the Phoenix configuration file if your certificate's private key requires a password. This is a bit much to describe here, and there is more than one way to do this, so if you need to go down this path and get stuck, let me know and I can help... and if we do this, I'd probably added the require options to the app, and describe it all in the `README.md`.
