### ISSUE TITLE
Rationalize $include to always be a list of strings

### ISSUE THREAD

**Issue by dkolbly** [ocsf/ocsf-schema#791]
The use of the `$include` directive is inconsistent; sometimes a string, but more often a list.  (It looks like before recently it was more often a single string value, but as of now there is only one occurrence of a bare string value).

I propose simplifying the meta-schema by requiring that `$include` be array-valued.

(This was discussed in Schema sync meeting on 26 September.)

cc @alanisaac this will allow the metaschema to drop the oneof clause for `$include` :rocket:

**Comment by alanisaac** [comment]
@dkolbly I believe this is closed as of the associated PRs above: `$include` is no longer allowed to be an individual string.  Feel free to reopen if I'm mistaken though!
