### ISSUE TITLE
DRAFT: user.type_id requirement specification

### ISSUE THREAD

**Issue by mikeradka** [ocsf/ocsf-schema#797]
This came up in our System Activity Workstream Sync on 09/27/2023.
We noticed that the `user` object's `type_id` requirement was set to `required` about two weeks ago. Was this perhaps an oversight? Mappers are finding that the type of user account appears to be unknown in more cases than it is known. Should this field remain required? Note: this field is optional in our release candidates, and concern is that change could have been breaking.

https://github.com/ocsf/ocsf-schema/blame/276247a3d85caa60cfa23205b9502bad6cc91077/objects/user.json#L69

<img width="512" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/91983279/7bee4355-cd3e-42b1-b888-120c9d6a0fa2">

**Comment by floydtree** [comment]
Great timing, I faced a similar issue, I just created an issue & PR that tries to alleviate this issue along with a few other issues. - https://github.com/ocsf/ocsf-schema/pull/796

**Comment by mikeradka** [comment]
This is updated in `v1.1.0-dev`. Since it is breaking, can not change in `v1.0.0`.
