### ISSUE TITLE
Change data type for `type_uid` to `long_t`

### ISSUE THREAD

**Issue by rohencz-s1** [ocsf/ocsf-schema#812]
When developing custom extensions for OCSF the generated value for `type_uid` can be out of range for classic 32-bit integer (max positive value is `2,147,483,647`). 

As an example, we (S1 - extension ID 996) have added a custom class (ID 1) under the findings category (ID 2) so the generated `class_uid = 99602001`. Based on the current expression how _type_uid_ is calculated, `class_uid * 100 + activity_id`, the final UID for the _unknown_ activity is `9960200100` which is out of range for the 32-bit integer. 

Would it be possible to change the data type for _type_uid_ to `long_t`? In case somebody is using the data type for generating some non-json schema the `long_t` type is better hint to use a 64-bit integer for it instead of 32-bit one as it's the case with `integer_t` used currently.

**Comment by rohencz-s1** [comment]
We have noticed this when we have generated proto files from the schema and tried to parse incoming json into it (the field value overflowed).

**Comment by rmouritzen-splunk** [comment]
Michael hit a similar issue internally (inside Splunk). 

Note that an OCSF Integer is defined as a "signed integer value" without specifying range. Since an OCSF Long is defined as a 64-bit signed integer, this implies that an OCSF Integer is a 32-bit signed integer, but this is certainly not explicitly stated.

We may need to refine or change the definition of OCSF Integer for 1.1, and perhaps refine the OCSF Long definition.

**Comment by rmouritzen-splunk** [comment]
A workaround that _probably_ will always work would be to use a 64-bit signed integer type for all occurrences of the OCSF Integer type.

Another interesting side note is that JSON (the encoding we assume basically all OCSF data is encoded in to) does not specify the range of its `number` type, though the JSON RFC mentions that for maximum compatibility, the integer range should be -2^53 + 1 to 2^53 - 1, just inside the allowed range of an IEEE double precision number. And note that JavaScript uses IEEE doubles for the JSON `number` type (unless tricks are used).

**Comment by rmouritzen-splunk** [comment]
IMHO, changing OCSF Integer to basically match the JSON Schema definition of Integer makes the most sense. The OCSF Long could then be defined as an alias for OCSF Integer, and possible be marked deprecated in favor of the Integer type.

https://json-schema.org/draft/2020-12/json-schema-core#name-range-of-json-values

> [6.1. ](https://json-schema.org/draft/2020-12/json-schema-core#section-6.1)[Range of JSON Values](https://json-schema.org/draft/2020-12/json-schema-core#name-range-of-json-values)
> An instance may be any valid JSON value as defined by [JSON](https://json-schema.org/draft/2020-12/json-schema-core#RFC8259) [[RFC8259](https://json-schema.org/draft/2020-12/json-schema-core#RFC8259)]. JSON Schema imposes no restrictions on type: JSON Schema can describe any JSON value, including, for example, null.

https://datatracker.ietf.org/doc/html/rfc8259#section-6

> Note that when such software is used, numbers that are integers and are in the range [-(2**53)+1, (2**53)-1] are interoperable in the sense that implementations will agree exactly on their numeric values.

**Comment by mikeradka** [comment]
This was addressed via https://github.com/ocsf/ocsf-schema/pull/928
