### ISSUE TITLE
"How to create an extension" documentation

### ISSUE THREAD

**Issue by jp-harvey** [ocsf/ocsf-schema#82]
Extension documentation is required for the initial OCSF release.

**Comment by paveljos** [comment]
Is this regarding contributions? Or a more general overview of extensions?

**Comment by jp-harvey** [comment]
Completed here: https://github.com/ocsf/ocsf-schema/blob/main/doc/extending-existing-class.md

**Comment by jp-harvey** [comment]
@rroupski to update the https://github.com/ocsf/ocsf-schema/blob/main/README.md#extending-the-schema section with some more detail and cleanup of inaccuracies.
