### ISSUE TITLE
MacOS extension has duplicate enum values

### ISSUE THREAD

**Issue by wjdingman1** [ocsf/ocsf-schema#850]
`startup_app_type_ids` has duplicate enum caption [Other](https://github.com/ocsf/ocsf-schema/blob/22c324330aae83829367a8ebba8dbd6c1d557b7f/extensions/macos/dictionary.json#L112-L123) in `1.1.0`.

Is this a mistake? If it is not, how should clients using this enum distinguish between the two?

**Comment by lukas-krecan-s1** [comment]
Just the clarify, the conflicting caption is 8 - "Other" which conflicts with 99

**Comment by lukas-krecan-s1** [comment]
@maxhotta any idea if it's a mistake or an intentional clash?

**Comment by wjdingman1** [comment]
Sorry, edited my comment 👍

**Comment by maxhotta** [comment]
Agree, Other is confusing here since we have 99.  It does have a specific meaning, and will update the name of the enum.
Thanks for the input.
