### ISSUE TITLE
Breaking change in kb_articles between 1.0.0 and 1.1.0-dev

### ISSUE THREAD

**Issue by lukas-krecan-s1** [ocsf/ocsf-schema#855]
This [commit](https://github.com/ocsf/ocsf-schema/commit/6d68e95dc3e4a5f2d2b35c4c44ae825556d0c4fa#diff-810a9d066ad684b612164d5182d14eba68ddabffc10908d99803e957692bb956R1798) changed `kb_articles` from `string_t` to `kb_article` which is a breaking change. Can you please revert the change?

**Comment by floydtree** [comment]
Good catch! I'll take a look

**Comment by jasonbreimer** [comment]
I created the following to resolve #855. A new dictionary field patch_list which can replace kb_articles. See https://github.com/ocsf/ocsf-schema/pull/862. However in yesterday's sync call it was also suggested to deprecate kb_articles as string_t. The group concern was duplication of content with kb_articles and patch_list containing the same data. I can go either way but it does seem strange to have two field/attributes that are basically the same. I also wonder if there isn't some way to allow this change to kb_articles but still support Lukas's needs.

**Comment by lukas-krecan-s1** [comment]
Hi, we do not have any needs for kb_articles yet. We have tests using samples generated by OCSF server and they started to fail after upgrade to 1.1.0-dev.

**Comment by pagbabian-splunk** [comment]
It makes sense then to deprecate `kb_articles` since it is also odd that it becomes an array of strings, while `patch_list` is an array of `kb_article`.  It's just not an intuitive or consistent way of modeling.
