### ISSUE TITLE
device.type_id does not have: firewall, router, switch, hub, utm

### ISSUE THREAD

**Issue by mikeradka** [ocsf/ocsf-schema#884]
`device.type_id` is missing `firewall`, `router`, `switch`, `hub`, and `utm` devices (unified threat management). We should add them to the device enums. I have a slew of events I am mapping from firewalls and utm devices, and in the future will likely be mapping logs from routers and switches.

<img width="1009" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/91983279/90ba0d27-9a9b-4607-a037-dd1d4a608d8c">

**Comment by Aniak5** [comment]
This sounds like a good idea to me

**Comment by mikeradka** [comment]
Closing this issue, work is complete.
