### ISSUE TITLE
Observables Description and type_id change   

### ISSUE THREAD

**Issue by zschmerber** [ocsf/ocsf-schema#891]
1.) It seems like Observable `"type": "File Hash", "type_id": 8` should be changed to just "Hash".  We want to represent all fingerprint hashes in the observable. (see below image)

<img width="1689" alt="hash" src="https://github.com/ocsf/ocsf-schema/assets/13574947/ab47f899-ce15-4e1d-894c-3125a09e6485">

  
This change would require a change to the observable Description. 
<img width="401" alt="image" src="https://github.com/ocsf/ocsf-schema/assets/13574947/61db7960-d91c-4952-8d1d-e2a8287ff83a">

2.) Each of the below Observables could be better served as a lower #. currently the values do not have representation in observables 1-10. 
`"type": "Geo Location", "type_id": 26` (value = location.coordinates)
`"type": "Registry Key", "type_id": 28`(value = reg_key.name)
`"type": "Registry Value", "type_id": 29` (value = reg_value.name)
`"type": "Container", "type_id": 27` (value = container.name)

**Comment by floydtree** [comment]
As discussed, Part 1 should be good for 1.1.0 and is merged. For Part 2, we'll need to create new data types and will require more deliberation, considering the timeline, we can take up part 2 for a future release.

**Comment by rmouritzen-splunk** [comment]
Looks like this was addressed. The `file_hash_t` type currently has a caption of "Hash". I was "File Hash" before this, matching the type. Seems like `file_hash_t` should have been called `hash_t`, but of course that would be a breaking change.
