### ISSUE TITLE
Demote `dst_endpoint` in DNS event class

### ISSUE THREAD

**Issue by Aniak5** [ocsf/ocsf-schema#899]
Currently the DNS event class has the `dst_endpoint` set to `required` and there are many logs that do not actually have a `dst_endpoint` populated such as Cloudflare DNS and Bind. Demote the `dst_endpoint` to be `recommended` rather than `required`.

**Comment by pagbabian-splunk** [comment]
Sounds right Ania.  We should demote it, non-breaking.
