### ISSUE TITLE
Move 'Network File Activity' and 'Email' classes to 'Application' category

### ISSUE THREAD

**Issue by mikeradka** [ocsf/ocsf-schema#905]
Network File Activity and Email Activity are much more based on the Application layer. The focal point of those logs are not the network transaction, but what the overarching applications are actually doing.

We are proposing to move these classes under the 'Application' category, which they are more appropriately suited.

Note: Doing so in a non-breaking manner will require class deprecation.

**Comment by mikeradka** [comment]
I don't recall us ever deprecating a class before. I am testing from my end, but it is possible that we might need to build a way to introduce class deprecation.

**Comment by mikeradka** [comment]
Per today's network call, we discussed the name of `Network File Activity` under `Application`

We are most likely landing on `File Sync & Share`

**Comment by Aniak5** [comment]
Some other options are: 

- Web File Services
- File Hosting Services
- File Hosting Activity
- Web File Activity

**Comment by mikeradka** [comment]
> Some other options are:
> 
> * Web File Services 
> * File Hosting Services
> * File Hosting Activity
> * Web File Activity

I would stray from `Web File Activity`, because this makes me think too much about the `HTTP PUT/DELETE` requests. `Web File Services` I think would also cause another circular discussion about "what is a web resource?", so I would opt against that to avoid the philosophical rabbit-hole.

Let's keep `File Sync & Share` and `File Hosting Activity` in the running for now.

**Comment by mikeradka** [comment]
Vote created here: https://github.com/ocsf/ocsf-schema/discussions/909

Please cast your vote!

**Comment by mikeradka** [comment]
Completed via #917

**Comment by mikeradka** [comment]
`Network File Activity` has been deprecated and replaced with `Application -> File Hosting Activity`.
Next will be a PR for the `Email` classes to move over to `Application`.

**Comment by mikeradka** [comment]
PR is in to move the Email File/URL classes. Once this is merged this Issue can be closed.

**Comment by mikeradka** [comment]
In 1.1 preparation, we determined that Email File and URL classes need some work, and that should precede moving them to the `Application` category. Thus, those two classes will not be moved for the `1.1` release.
