### ISSUE TITLE
Base Network class should not include activity_id

### ISSUE THREAD

**Issue by pagbabian-splunk** [ocsf/ocsf-schema#913]
The `network.json` file is the category base for the Network Activity.  It defines the `activity_id` attribute that shouldn't assume all extended classes share the same values.  (There is a behavior of the server that also kicks in - if the extending class overrides `activity_id` and has fewer items, those items are overridden but the additional items are brought in from the base.  This is not a good way to develop, and can have side effects).

Although not a hard fast rule, `activity_id`s should be paired with `class_uid` and reflected directly in the class via `type_uid`.

I suggest we remove the `activity_id` from `network.json` and each extending class should specifically define the `activity_id`.

This isn't always a problem, e.g. for `Discovery` all of the extending classes purposely share the same two `activity_id`s.  Similarly for the `Finding` category.  `System` `IAM` and `Application` already delegate to the extending classes.

**Comment by Aniak5** [comment]
@pagbabian-splunk this makes sense to me. This will prevent a class from automatically inheriting `activity_id`s from an extended base class if the inheriting class has defined fewer `activity_id`s  within it.
