### ISSUE TITLE
Move Email File Activity and Email URL Activity to Application category

### ISSUE THREAD

**Issue by mikeradka** [ocsf/ocsf-schema#927]
(spun off from #905)

Email Activity are much more based on the Application layer. The focal point of those logs are not the network transaction, but what the overarching applications are actually doing.

We are proposing to move these classes under the 'Application' category, which they are more appropriately suited.

Note: Doing so in a non-breaking manner will require class deprecation.

**Comment by jonrau-at-queryai** [comment]
We deprecated both of these in #1259
