### ISSUE TITLE
Rename `metadata.schema_extension_list` back to `metadata.extensions`

### ISSUE THREAD

**Issue by lukas-krecan-s1** [ocsf/ocsf-schema#945]
Please, revert https://github.com/ocsf/ocsf-schema/pull/934. My reasons why I think it's a good idea.

1. There are users that are already building on top of 1.1.0-dev, this change is going to cause lot of headaches to them. For example, one of the reasons we took the risk to use 1.1.0-dev was that we needed to specify multiple extensions, which was impossible in 1.0.0
2. I do not expect anyone to confuse `metadata.extensions` with `tls.extension_list`. I can't imagine a scenario when it could happen.
3. `tls.extension_list` is actually deprecated since 1.1.0
4. It's called "Extensions" in OCSF server UI, you are adding a new extension to an `extension` directory, the new name is actually more confusing to me.

**Comment by lukas-krecan-s1** [comment]
@floydtree Can you please address this before [1.1.0 release](https://github.com/ocsf/ocsf-schema/pull/947)? 🙏

**Comment by floydtree** [comment]
Currently, OCSF has an even mix of plural, `_list` suffix in the names of array-type attributes. The intention of the change you referred to was to bring about consistency in such attributes across OCSF by aligning to a single convention. But considering your points and the number of other such attributes that we have today, we established that we need to have a broader convention for naming of array-type attributes and decided to revert `schema_extension_list` to `extensions`.  

As an outcome of this decision, we'll be updating OCSF's conventions/guidelines about naming array type fields to include both plural and `_list` for arrays, pending further discussions. cc @pagbabian-splunk @zschmerber @mikeradka @Aniak5

**Comment by lukas-krecan-s1** [comment]
Thank you
