### ISSUE TITLE
Setting "ip" and "mac" to be is_array:True

### ISSUE THREAD

**Issue by alvinnieto** [ocsf/ocsf-schema#968]
For devices with different network connections, there are cases where in a device is assigned two or more IP and MAC addresses depending on the number of their network interface cards (physical or virtual).

Would it be possible to add **"is_array": true** to the dictionary for ip and mac objects? This may be a breaking change, but it will certainly help when investigating with the logs that have complete information on the IP and MAC addresses, including IPv4 and IPv6, to be able to correlate events.

From dictionary.json
>     "ip": {
>       "caption": "IP Address",
>       "description": "The IP address, in either IPv4 or IPv6 format.",
>       "type": "ip_t"
>     },
>     "mac": {
>       "caption": "MAC Address",
>       "description": "The Media Access Control (MAC) address that is associated with the network interface.",
>       "type": "mac_t"
>     },

Here is an example of the output:

>     "device": {
>       "hostname": "OCSF-VM",
>       "ip": [
>         "fe80::8000:dddd:ccc:1111",
>         "169.254.27.207",
>         "fe80::8000:dddd:ccc:1112"
>         "169.254.27.208"
>       ],
>       "mac": [
>         "00:11:22:33:55:66",
>         "00:11:22:33:44:67"
>       ]
>     }

**Comment by pagbabian-splunk** [comment]
Check out the `device.network_interfaces` array attribute: each `Network Interface` has an `ip` and `mac` attribute which would allow you to map the above.  The `device.ip` and `device.mac` attributes would be the interface from which traffic is relevant to the specific instance of the event (which should also be in the list of interfaces).  For an inventory collection event, e.g. a `Discovery` event, the `device.ip` and `device.mac` can be any of the addreses.

**Comment by alvinnieto** [comment]
Thanks for clarifying @pagbabian-splunk 

We can go with the device.network_interfaces route.
