### ISSUE TITLE
How do we use this in AWS-CDK?

### ISSUE THREAD

**Issue by sholtomaud** [ocsf/ocsf-schema#975]
How do we use this in AWS-CDK?

**Comment by floydtree** [comment]
Can you elaborate on the specifics of your ask? OCSF is a schema framework to model security events, not sure what you mean by using this in AWS-CDK.

**Comment by sholtomaud** [comment]
Sorry, just saw your reply. AWS-CDK is a framework for building cloud infra. I assume OCSF can be used for cloud infra? If so how could we integrate it with CDK?
